### ISSUE TITLE
[多标签Tab页] tab不美观，与整体页面色调、样式违和

### ISSUE THREAD

**Issue by wmhost** [Tencent/tdesign-vue-next-starter#103]
### 这个功能解决了什么问题

完善tab页显示效果

### 你建议的方案是什么

1、标签色调、高度建议调优，与整体页面框架匹配
2、已激活状态下的标签高度与未激活的标签高度保持一致
3、右键功能关闭左侧支持允许不关闭最左侧主页标签
4、目前右键功能仅支持已激活状态下标签，希望全部标签都允许右键功能

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/34067541/160066308-f7a48b80-d0b9-41cf-9f29-951e50134a77.png">

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/34067541/160066328-12d85b1d-4e1f-4a09-9bde-c5f52fe2069e.png">

**Comment by uyarn** [comment]
谢谢反馈 发上来也是希望看看有没有更多建议 针对这几点我们再做一些优化

**Comment by aurthurxlc** [comment]
建议添加刷新按钮

**Comment by uyarn** [comment]
> 建议添加刷新按钮

刷新按钮有的呢
