### ISSUE TITLE
[多标签Tab页] 启用多标签Tab页时，打开多个页签然后在浏览器地址栏刷新页签丢失

### ISSUE THREAD

**Issue by dwlegend** [Tencent/tdesign-vue-next-starter#105]
### tdesign-vue-next-starter 版本

能重现

### 重现链接

https://github.com/Tencent/tdesign-vue-next-starter

### 重现步骤

第一步：设置栏启用 【使用 多标签Tab页】，复制最新配置到代码处修改为isUseTabsRouter: true；
第二步：重新加载项目，同时点击多个菜单，此时存在多个tab页签，然后到浏览器地址栏处点击刷新或地址按回车键刷新，tab页签会丢失，只剩当前页签。

### 期望结果

当前tab页面在浏览器地址栏刷新，不应该导致其他tab页签丢失。

### 实际结果

当前tab页面在浏览器地址栏刷新，其他已经打开的tab页签会丢失。

### 框架版本

vue 3.2.31

### 浏览器版本

 99.0.4844.82

### 系统版本

win10

### Node版本

v14.17.5

### 补充说明

1、个人推断出现此问题原因是 浏览器刷新导致 pinia中useTabsRouterStore的tabRouterList数据丢失，从而导致界面页签丢失。

**Comment by uyarn** [comment]
谢谢反馈  刷新保留需要再增加localStorage来做 不太确定实际使用保留需求更多还是不保留更多所以没有加上 做开关也不太方便展示 所以按没有保留的发生实现了 接下来我们在代码里增加这个配置吧

**Comment by dwlegend** [comment]
嗯嗯，好的，谢谢。我也是在用tdesign做项目时才发现的这个问题。之前用antd和el的一些成熟后台框架，浏览器刷新其他页签会被保留的，只是对当前页签单独进行刷新。

**Comment by 94dreamer** [comment]
已收到，谢啦
