### ISSUE TITLE
后台框架自适应移动端

### ISSUE THREAD

**Issue by 23022340** [Tencent/tdesign-vue-next-starter#117]
### 这个功能解决了什么问题

新增后台框架部分的移动端自适应，在部分场景下有移动端需求，建议在现有框架基础上增加自适应。

### 你建议的方案是什么

新增后台框架部分的移动端自适应，在部分场景下有移动端需求，建议在现有框架基础上增加自适应。当在手机使用时，将框架菜单制作为左侧抽屉式菜单，顶部多余操作按钮不显示。内容区用户根据自己需要自己做自适应

**Comment by uyarn** [comment]
@23022340 我们接下来要做移动端的支持的 但是不是自适应 而是另一种方式 如果你有兴趣参与这个方案的实施 或者有实际场景的使用分享 可以联系我
