### ISSUE TITLE
图标无法离线使用

### ISSUE THREAD

**Issue by shuax** [Tencent/tdesign-vue-next-starter#122]
### 这个功能解决了什么问题

因为是在内网使用，无法连接外网，显示不了icon。

### 你建议的方案是什么

增加离线使用方式。

**Comment by uyarn** [comment]
@shuax 参考这个discussion的处理方式呢 https://github.com/Tencent/tdesign-vue/discussions/747?converting=1

**Comment by shuax** [comment]
> @shuax 参考这个discussion的处理方式呢 [Tencent/tdesign-vue#747](https://github.com/Tencent/tdesign-vue/discussions/747)

手动下载资源加到自己工程可以显示图标了，`loadDefaultIcons `不知道在哪儿设置。

**Comment by uyarn** [comment]
> > @shuax 参考这个discussion的处理方式呢 [Tencent/tdesign-vue#747](https://github.com/Tencent/tdesign-vue/discussions/747)
> 
> 手动下载资源加到自己工程可以显示图标了，`loadDefaultIcons `不知道在哪儿设置。

后面我们加个FAQ具体说明一下这个使用方式；

`loadDefaultIcons不知道在哪儿设置。`
1. 把我们的https://tdesign.gtimg.com/icon/default-demo/index.js 这个svgsprite资源复制一份上传到任何你可以访问的地址，如`http://127.0.0.1/icon.js`；
2. 创建一个新的组件比如`<local-icon /> ` 这个icon是对icon的封装 url使用你步骤1可以访问的地址，如
```
<template>
 <Icon url="http://127.0.0.1/icon.js" name="name" />
</template>
import { Icon } from 'tdesign-icons-vue-next'
```
在你的项目中替换掉之前的
`<t-icon name="name"/>` 为`<local-icon name="t-icon-name" />`
 如果还有问题，可以企微找我或者加我WeChat交流

**Comment by shuax** [comment]
好的，感谢解答，反正现在能用了。
