### ISSUE TITLE
npm i tdesign-vue-next 安装过程中失败

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next-starter#124]
![image](https://user-images.githubusercontent.com/78259973/163748665-e1eb5f55-c260-4ce7-a601-d5e6eb8703c0.png)

PS F:\study\tdesign-starter> npm i tdesign-vue-next
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'F:\\study\\tdesign-starter\\node_modules',
npm WARN cleanup     [Error: EPERM: operation not permitted, unlink 'F:\study\tdesign-starter\node_modules\dayjs\locale\is.js'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'unlink',
npm WARN cleanup       path: 'F:\\study\\tdesign-starter\\node_modules\\dayjs\\locale\\is.js'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! network Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xmlc\AppData\Local\npm-cache\_logs\2022-04-18T03_04_44_934Z-debug-0.log

**Comment by uyarn** [comment]
安装其他包会不会失败呢 看error message是你自己目录permission的问题

**Comment by synctimes163** [comment]
![image](https://user-images.githubusercontent.com/78259973/163795024-ff66e6c3-dc1c-466d-9336-b0afc0a4fb47.png)

我用vscode 工具重新试了几次可以，谢谢

**Comment by uyarn** [comment]
没有问题这个issue我关闭咯
