### ISSUE TITLE
使用按需引用插件时，运行报错

### ISSUE THREAD

**Issue by wmhost** [Tencent/tdesign-vue-next-starter#125]
### tdesign-vue-next-starter 版本

0.2.1

### 重现步骤

yarn add -D unplugin-vue-components unplugin-auto-import

yarn dev

<img width="1379" alt="wecom-temp-8a48c26c65da4b2286ab8a338c3e5b7b" src="https://user-images.githubusercontent.com/34067541/163951342-bea51b24-c553-4d6e-9a23-20a864756d5c.png">

### 期望结果

正常使用

**Comment by uyarn** [comment]
已经更新插件 https://github.com/antfu/unplugin-vue-components 等它发新版本
