### ISSUE TITLE
分割菜单模式，一级菜单未被点亮，搜索框的图标离边框太远

### ISSUE THREAD

**Issue by JokerLoLgrey** [Tencent/tdesign-vue-next-starter#126]
### tdesign-vue-next-starter 版本

Vue Next for Web 0.12

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/user/index

### 重现步骤

切换为分割菜单模式，一级菜单未被点亮
![image](https://user-images.githubusercontent.com/33446705/164198109-a6c25504-02fe-41c2-a7c8-5cd30e891621.png)

搜索框图标离边框太远
![image](https://user-images.githubusercontent.com/33446705/164197951-ad84f4c4-a32f-4c41-a555-4fd203de4b37.png)

### 期望结果

切换为分割菜单模式，一级菜单被点亮，但是希望不要像vue2版本一样不是很明显

vue2版本
![image](https://user-images.githubusercontent.com/33446705/164198277-1e9c3908-67a0-4f99-9013-135e6222c1a9.png)

希望能够在vue2版本基础上加深一下颜色，使得第一级菜单被点亮更加显眼

**Comment by uyarn** [comment]
fixed by @kerwin612
