### ISSUE TITLE
结果页能否加一个系统维护中

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next-starter#128]
### 这个功能解决了什么问题

结果页能否加一个系统维护中 ，用于版本更新后再使用

### 你建议的方案是什么

结果页加一个系统维护中
![image](https://user-images.githubusercontent.com/78259973/164610921-1eb2a488-5bf5-4525-9c3a-800bbed55459.png)

**Comment by pattybaby110** [comment]
收到～ 感觉设计可以出一个方案～

**Comment by uyarn** [comment]
已新增
