### ISSUE TITLE
新增权限管理相关示例代码

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue-next-starter#137]
### 这个功能解决了什么问题

此issue可以讨论和跟进任意和权限管理功能相关的代码的想法

### 你建议的方案是什么

新增权限管理相关示例代码

**Comment by fz-lyle** [comment]
认领该任务，预计5月7日前提交

**Comment by 4566704** [comment]
提交的链接在哪？想参考一下

**Comment by uyarn** [comment]
> 提交的链接在哪？想参考一下

还没增加 移步到#150 这个issue先关闭了
