### ISSUE TITLE
全面基于CSS Token改造

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue-next-starter#149]
### 这个功能解决了什么问题

Starter项目此前基于less的方案做了一些定制的样式，同时掺杂了不少过渡阶段的代码，配合接下来TDesign的整体设计，包括主题生成器等功能，需要将整体方案都切换到基于CSS Token来做。

### 你建议的方案是什么

1. 移除目前掺杂在代码中的TDesign的less文件
2. 处理组件中使用TDesign less vars的地方，改为使用CSS Token

**Comment by uyarn** [comment]
- [ ] 将代码中涉及修改token的代码修改为改变CSS Token来实现 e.g.,https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/pages/dashboard/base/components/overview.vue#L197 @text-color-placeholder 替换为var(--td-text-color-placeholder)
- [ ] 移除冗余在项目中的组件库less variables代码 , https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/style/variables.less
- [ ] 调整主题配置中的逻辑 涉及less var的逻辑需要改为CSS Token的逻辑, 这部分包括组件库本身的替换以及图表颜色的替换 e.g., https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/utils/color.ts#L21 https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/config/color.ts#L28

**Comment by wincheer** [comment]
基于 CSS Token改造更应该放到TDesign的组件库中作为原生支持，而不是放到Starter中实现

**Comment by uyarn** [comment]
> 基于 CSS Token改造更应该放到TDesign的组件库中作为原生支持，而不是放到Starter中实现

TDesign的组件库本身就是基于CSS Token 这边只是把多余再转换为less vars的一层去掉
