### ISSUE TITLE
使用cli工具构建项目一直clone失败

### ISSUE THREAD

**Issue by lovae** [Tencent/tdesign-vue-next-starter#15]
使用官网的`td-starter init`命令，初始化模板时，git clone一直失败，不论vue2还是vue3。node v16.13.0

**Comment by xnng** [comment]
我也是一直卡在 `⠴ 正在构建模板...`

**Comment by Eden-Harris** [comment]
👉  开始构建，请稍侯.

✖ ❗错误：下载模板失败
❗错误信息： Error: 'git clone' failed with status 128

**Comment by uyarn** [comment]
请参考这里 https://tdesign.tencent.com/starter/docs/feedback
或这个issue https://github.com/Tencent/tdesign-vue-starter/issues/26 处理一下

接下来也会升级cli避免这个流程。

**Comment by uyarn** [comment]
请重新install一下 tdesign-starter-cli 
`npm installl tdesign-starter-cli@latest -g`
