### ISSUE TITLE
希望后台管理系统模板能够出配套的后端代码，包含菜单权限、账号管理、角色管理、组织（部门）管理、个人中心的模板代码

### ISSUE THREAD

**Issue by JokerLoLgrey** [Tencent/tdesign-vue-next-starter#150]
### 这个功能解决了什么问题

能够真正做到模板下载后就可以自定义开发

### 你建议的方案是什么

菜单权限：涉及菜单及按钮权限新建、编辑、删除以及菜单和按钮支持内嵌和外链第三方网站
账号管理：涉及账号的新建、编辑、删除及多个角色的分配以及所属组织（部门）的分配
角色管理：涉及角色的新建、编辑、删除及可访问菜单按钮权限的分配以及删除角色后对应的账号角色重新分配问题
组织（部门）管理：涉及组织（部门）的新建、编辑、删除以及删除组织（部门）后对应的账号组织（部门）重新分配问题
个人中心：昵称、头像、真实姓名、联系电话等等的修改

**Comment by h7ml** [comment]
> ### 这个功能解决了什么问题
> 能够真正做到模板下载后就可以自定义开发
> 
> ### 你建议的方案是什么
> 菜单权限：涉及菜单及按钮权限新建、编辑、删除以及菜单和按钮支持内嵌和外链第三方网站 账号管理：涉及账号的新建、编辑、删除及多个角色的分配以及所属组织（部门）的分配 角色管理：涉及角色的新建、编辑、删除及可访问菜单按钮权限的分配以及删除角色后对应的账号角色重新分配问题 组织（部门）管理：涉及组织（部门）的新建、编辑、删除以及删除组织（部门）后对应的账号组织（部门）重新分配问题 个人中心：昵称、头像、真实姓名、联系电话等等的修改

老哥怎么把自己的业务需求往下面提呀..

**Comment by wincheer** [comment]
支持这个功能，这样才真正做到即开即用。

**Comment by rzshuo** [comment]
强烈不建议做后端代码，这个项目开发人员的时间应该用在TDesign本身上。

**Comment by hxywuya** [comment]
不建议做后端代码，而是应该做约定，比方说权限管理有哪些功能，每个功能涉及一些什么字段，然后这些字段默认叫什么，然后支持改别名

**Comment by xiangyouyu** [comment]
看别人刚整了一套对接后端java的 :   design.frsimple.cn

**Comment by timi137137** [comment]
关于`能够真正做到模板下载后就可以自定义开发`这件事，主要问题在于你们需要简洁还是要从别人已经做好的基础上开发
比如说：
简洁的话就是这个项目只帮你做好了样式大概的样子，里面有的只是很基础通用的代码，你打开来编译或者增删都简单，大小也不大
如果从别人已经做好的企业中后台项目的基础上开发，那么就是里面有别人规范好方便使用的代码，让你可以添加文件照抄就能个改就能用，但是弊端是你没办法改核心代码，很容易导致项目出错，并且编译大小可能会很大。这才是要讨论的方向

关于后端，本身就不应该由前端负责，前端最多附带mock，如果是上面的后者则可以完美做一套mock数据。
