### ISSUE TITLE
系统设置>页面设置 开启“使用多标签Tab页”选项经常导致页面无响应

### ISSUE THREAD

**Issue by M-zj** [Tencent/tdesign-vue-next-starter#169]
### tdesign-vue-next-starter 版本

16.0

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/dashboard/base

### 重现步骤

页面设置开启 多页签 时经常会出现页面无响应，偶尔也正常。
![微信图片_20220614162058](https://user-images.githubusercontent.com/58452064/173529956-101e819d-1dd5-4416-bf4f-5034e88b8d83.png)

### 期望结果

开启多页签正常

**Comment by kerwin612** [comment]
和 #166 属于同一个问题；已修复，见 #168 ；
