### ISSUE TITLE
[Utils] 关于请求工具封装

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next-starter#183]
### 这个功能解决了什么问题

在本模板中，只有utils/request.js 是请求工具的封装，为了方便使用，我建议可以添加src/api文件夹，将项目中出现的API做打包处理，并将request进行更深层次的封装。

### 你建议的方案是什么

例如:
src/api/login.ts
```ts
import request from "@/utils/request";
import { LoginParams, LoginResultModel } from '@/api/model/loginModel.ts';

enum Api {
  Login = '/login',
}

export function loginApi(params: LoginParams) {
  return request.post<LoginResultModel>({ url: Api.Login, params });
}

```

src/api/model/loginModel.ts
```ts
export interface LoginParams {
  // 用户名
  account: string;
  // 密码
  password: string;
}

export interface LoginResultModel {
  // UID
  _id: number;
  // 用户名
  username: string;
  // 手机
  mobile: string;
  // 头像
  avatar: string;
  // 邮件
  email: string;
}
```

其中关于request.post方法，是因为深度封装的缘故，部分代码如下
```ts
  post<T = any>(config: AxiosRequestConfig, options?: RequestOptions): Promise<T> {
    return this.request({ ...config, method: 'POST' }, options);
  }
```

此做法对TS有极大的兼容性和易用性，能很好地利用TS的类型约束（题外话：很像C#）
如果觉得做法没问题的话，我可以封装好后提PR。辛苦各位

**Comment by uyarn** [comment]
可以有 不过现在模板里大部分的demo都是简单的get请求示例 可以同时增加一些复杂参数的请求 比如login这个可以改造下来做示例

**Comment by timi137137** [comment]
> 可以有 不过现在模板里大部分的demo都是简单的get请求示例 可以同时增加一些复杂参数的请求 比如login这个可以改造下来做示例

但是目前遇到一个问题，本模板是基于Vue2改过来的吗，如果要完全改向TS的话可能需要添加types文件夹等物件，可能稍微有点庞大

**Comment by uyarn** [comment]
> > 可以有 不过现在模板里大部分的demo都是简单的get请求示例 可以同时增加一些复杂参数的请求 比如login这个可以改造下来做示例
> 
> 但是目前遇到一个问题，本模板是基于Vue2改过来的吗，如果要完全改向TS的话可能需要添加types文件夹等物件，可能稍微有点庞大
> 
> 例如：将部分ESLint规则关闭，不然没有办法封装

不全是 不过request部分很多是 类型上很多没描述清楚。然后 没理解为什么完全改向ts需要添加types文件夹

**Comment by timi137137** [comment]
> > > 可以有 不过现在模板里大部分的demo都是简单的get请求示例 可以同时增加一些复杂参数的请求 比如login这个可以改造下来做示例
> > 
> > 
> > 但是目前遇到一个问题，本模板是基于Vue2改过来的吗，如果要完全改向TS的话可能需要添加types文件夹等物件，可能稍微有点庞大
> > 例如：将部分ESLint规则关闭，不然没有办法封装
> 
> 不全是 不过request部分很多是 类型上很多没描述清楚。然后 没理解为什么完全改向ts需要添加types文件夹

因为要添加新类型的相关描述，如

```ts
export interface RequestOptions {
  // Splicing request parameters to url
  joinParamsToUrl?: boolean;
  // Format request parameter time
  formatDate?: boolean;
  // Whether to process the request result
  isTransformResponse?: boolean;
  // Whether to return native response headers
  // For example: use this attribute when you need to get the response headers
  isReturnNativeResponse?: boolean;
  // Whether to join url
  joinPrefix?: boolean;
  // Interface address, use the default apiUrl if you leave it blank
  apiUrl?: string;
  // 请求拼接路径
  urlPrefix?: string;
  // Error message prompt type
  errorMessageMode?: ErrorMessageMode;
  // Whether to add a timestamp
  joinTime?: boolean;
  ignoreCancelToken?: boolean;
  // Whether to send token in header
  withToken?: boolean;
}
```

因为该封装是基于其他项目，因此会做出修改，在这仅做参考

**Comment by uyarn** [comment]
噢 这个如果完善是要增加 其实现在还有个interface.ts 也可以改造一下 一起放在types文件加里  或者继续往Interface里增加 （这个没有太明确的想法 毕竟目前默认定义的types也不多 不过如果增加types文件夹 我可能需要确认一下CLI那边受不受影响了

**Comment by timi137137** [comment]
> 噢 这个如果完善是要增加 其实现在还有个interface.ts 也可以改造一下 一起放在types文件加里 或者继续往Interface里增加 （这个没有太明确的想法 毕竟目前默认定义的types也不多 不过如果增加types文件夹 我可能需要确认一下CLI那边受不受影响了

CLI那边的PR还没人看呢.....(x
这个改造有一点大，需要我拆分PR吗还是就一个PR就行，我这边也是刚好有项目想用TD，顺便就来提贡献了，多有打扰请见谅

**Comment by uyarn** [comment]
> > 噢 这个如果完善是要增加 其实现在还有个interface.ts 也可以改造一下 一起放在types文件加里 或者继续往Interface里增加 （这个没有太明确的想法 毕竟目前默认定义的types也不多 不过如果增加types文件夹 我可能需要确认一下CLI那边受不受影响了
> 
> CLI那边的PR还没人看呢.....(x 这个改造有一点大，需要我拆分PR吗还是就一个PR就行，我这边也是刚好有项目想用TD，顺便就来提贡献了，多有打扰请见谅

welcome~~ CLI那边也是的PR还没看sorry >.< 
拆多个PR可以的 先完善下request部分的类型定义，再增加api层然后改造现在项目里发起请求的代码？

**Comment by timi137137** [comment]
> > > 噢 这个如果完善是要增加 其实现在还有个interface.ts 也可以改造一下 一起放在types文件加里 或者继续往Interface里增加 （这个没有太明确的想法 毕竟目前默认定义的types也不多 不过如果增加types文件夹 我可能需要确认一下CLI那边受不受影响了
> > 
> > 
> > CLI那边的PR还没人看呢.....(x 这个改造有一点大，需要我拆分PR吗还是就一个PR就行，我这边也是刚好有项目想用TD，顺便就来提贡献了，多有打扰请见谅
> 
> welcome~~ CLI那边也是的PR还没看sorry >.< 拆多个PR可以的 先完善下request部分的类型定义，再增加api层然后改造现在项目里发起请求的代码？

OK，那我尽快完成(? 然后我填了那个贡献问卷来着，我想问问有没有交流群什么的，有些个别小问题会想咨询一下之类的

**Comment by timi137137** [comment]
> <img alt="image" width="662" src="https://user-images.githubusercontent.com/26377630/175008090-65627b85-f0d9-4741-9ef0-267f1c05d22e.png">
> 
> 这个~

OK感谢~
