### ISSUE TITLE
已有问题待解决表单

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next-starter#186]
- [x] 是否开启反向代理- 目前项目中代理有严重的问题，proxy与axios配置完全不对（但是能用）
- [x] axios重新封装后未归类API文件夹
- [x] axios重新封装后文档未重写
- [ ] token增删有点疑惑 - 好像持久化了，又好像没有（？）
       是否添加pinia-plugin-persistedstate做持久化
- [x] 权限系统之谜 - 到底用的是什么权限筛选方法呢（？）
- [x] 写一个issue自动贴标签
- [x] 如果改写了prefix但是不改src/style/variables.less会造成样式缺失需要写文档

**Comment by timi137137** [comment]
[ 权限系统之谜 - 到底用的是什么权限筛选方法呢（？）]

关于这个我希望能搞清楚我们要用的是什么权限方式
目前看见的是在meta里加个roleCode，但是通常RABC权限模型用的都是权限节点，也就是
```
permission: [ 'dashboard', 'setting', 'user' ]
```
然后通过筛选其中的权限节点实现动态路由，目前我倒是看见了主路由不需要判断权限节点。但是子路由的话会很迷惑，想知道各位怎么想的，是采用权限节点还是采用什么方式

**Comment by uyarn** [comment]
RABC我理解作为这种偏后台通用的页面模板是比较通用的 但是之前对权限这块并没有很完整地设计 只是有一段相关代码给使用者随意发挥 所以你也看到了前面两个issue还在讨论要怎么做
