### ISSUE TITLE
【问题】请问怎么更换logo???

### ISSUE THREAD

**Issue by jamesz2011** [Tencent/tdesign-vue-next-starter#192]
### 这个功能解决了什么问题

请问怎么更换logo???
![image](https://user-images.githubusercontent.com/16397200/175813418-a5deeb2c-8b01-4426-a7c1-e107073f79d1.png)

### 你建议的方案是什么

help

**Comment by uyarn** [comment]
这里的Logo对应的是 assets/asset-logo-full 和 assets/asset-t-logo 这两个SVG 分别对应菜单展开和收起两种状态你可以替换成自己的
