### ISSUE TITLE
多标签模式

### ISSUE THREAD

**Issue by gh-ray** [Tencent/tdesign-vue-next-starter#21]
请问后续是否有支持多标签模式的计划呢？

**Comment by pengYYYYY** [comment]
多标签模式具体是指什么

**Comment by gh-ray** [comment]
就点击某一菜单，对应的打开一个tab页
<img width="378" alt="WX20211227-234454@2x" src="https://user-images.githubusercontent.com/7351367/147487188-1ac7e391-a2ae-4c50-a3f3-e208acf87a0c.png">

**Comment by pengYYYYY** [comment]
暂时没有这一块的设计，我们会做讨论。

**Comment by gh-ray** [comment]
尝试下先

**Comment by HollowWater** [comment]
多标签这个真的挺棒！！！！ 如果作者会加入这块代码的话，我就又增加了摸鱼时间

**Comment by jellydong** [comment]
同样需要这个功能

**Comment by pengYYYYY** [comment]
在规划中，下个大版本会加
