### ISSUE TITLE
希望vue-next-starter可以接入乾坤

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next-starter#220]
### 这个功能解决了什么问题

如果是多套业务都是由不同的人员开发，想集成这些业务作为一个系统，刚好可以用 vue-next-starter 作为主应用来接入其他业务的子引用

### 你建议的方案是什么

这个后台框架模板很不错，如果可以接入子应用就更好了，可以减少一些时间成本

**Comment by timi137137** [comment]
这个项目是基于TD的组件库制作的一个中后台即开即用方案，可能不会选择接入其他子应用，否则会让项目变得臃肿，毕竟这个项目会设计很多不同的人去开发使用。

**Comment by pengYYYYY** [comment]
这个项目一方面是对TD的品牌展示，另外一方面是对组件库一些通用使用的封装，官方不会去接入乾坤这类项目，可以看看有没有其他开发中做这一块的实践。

**Comment by hxywuya** [comment]
不懂就问，乾坤是什么？

**Comment by luoyu-233** [comment]
> 不懂就问，乾坤是什么？

就是微前端，具体你可以百度看看乾坤

**Comment by hxywuya** [comment]
> 就是微前端，具体你可以百度看看乾坤

百度了 全是八卦阵
