### ISSUE TITLE
[Menu]左侧导航菜单分组

### ISSUE THREAD

**Issue by 3fun4** [Tencent/tdesign-vue-next-starter#222]
基础组件的示例中，有可分组的侧边导航：https://tdesign.tencent.com/vue-next/components/menu#%E5%8F%AF%E5%88%86%E7%BB%84%E7%9A%84%E4%BE%A7%E8%BE%B9%E5%AF%BC%E8%88%AA

以上链接所指向的示例中的“Classification A”、“Classification B”……，在 starter 中如何实现？

**Comment by timi137137** [comment]
什么叫菜单分类？请描述清晰

**Comment by 3fun4** [comment]
修改了描述。starter的文档里，路由和菜单这块没有提到可分组的导航菜单，是需要修改其它文件吗？

**Comment by timi137137** [comment]
这个项目为了开箱即用，没有打包太多的功能进去，你可以在`src/layouts/components`中自定义你想要的功能，这个功能可以讨论存在的可行性

**Comment by 3fun4** [comment]
好的，谢谢！
