### ISSUE TITLE
[图表] echart无法自适应屏幕

### ISSUE THREAD

**Issue by yaxnice** [Tencent/tdesign-vue-next-starter#231]
### tdesign-vue-next-starter 版本

0.3.5

### 重现步骤

点击缩小左侧菜单栏的按钮将菜单栏缩小

### 期望结果

echart随着窗口的大小自适应[](url)

### 实际结果

无法自适应窗口大小

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/179159468-99d7500a-9175-44d2-aac6-b6744465ef4c.png)
能不能先学会填写版本号

**Comment by yaxnice** [comment]
版本是0.3.5

**Comment by timi137137** [comment]
https://user-images.githubusercontent.com/36812439/179160461-b04017f8-139e-4573-a330-2e2c7c8f72b6.mp4

未发现问题，请提供截图或详细描述

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/179160535-ecc4aafd-035f-417f-8964-5de8fec547f8.png)
![image](https://user-images.githubusercontent.com/36812439/179160561-8d160bb5-cdfa-44b4-a806-c236e616e172.png)

**Comment by yaxnice** [comment]
一开始我用Edge浏览器,后来我下载了最新版本的google浏览器依然会出现这样的问题
![屏幕截图 2022-07-15 101259](https://user-images.githubusercontent.com/87602183/179160661-f2418cfa-94be-4927-b68a-d1bdf4ba5eda.png)
![屏幕截图 2022-07-15 101346](https://user-images.githubusercontent.com/87602183/179160680-6b63348a-d541-4645-922b-0d7d363c1fd3.png)

**Comment by timi137137** [comment]
这个也是样式的问题，归类到 #235

**Comment by yaxnice** [comment]
这是线上地址预览的同样会出现这个问题
![CPT2207151422-1465x738](https://user-images.githubusercontent.com/87602183/179163864-bc1825f1-40ce-4447-9603-32d3f2ce0cf7.gif)

**Comment by yaxnice** [comment]
首页这个统计数据的图,如果使用window.onresize来触发echart的resize就可能出BUG,因为在收起侧边栏的时候,window的尺寸并不会变化,所以应该是监听echart容器的大小变化, 我是初学者如果逻辑有问题,请指出.

**Comment by timi137137** [comment]
done 
- #253
