### ISSUE TITLE
标签页设计不合理

### ISSUE THREAD

**Issue by yaxnice** [Tencent/tdesign-vue-next-starter#232]
### tdesign-vue-next-starter 版本

能

### 重现步骤

想搞几个标签页,然后右键这几个中不活跃的那一个

### 期望结果

出现右键菜单

### 实际结果

没有出现右键菜单,只有右键活跃的标签页才会出现邮件菜单

### 浏览器版本

Edge

### 系统版本

windows11

### Node版本

16

### 补充说明

应该点击每一个标签页都出现都出现右键菜单.

**Comment by uyarn** [comment]
改 确实当初是按这个逻辑去设计开发的 这样会需要使用者点击这个tab之后才能做其他操作 下个版本调整这个逻辑

**Comment by yaxnice** [comment]
好的
