### ISSUE TITLE
代码规范

### ISSUE THREAD

**Issue by yaxnice** [Tencent/tdesign-vue-next-starter#233]
### tdesign-vue-next-starter 版本

能

### 补充说明

能否完善一下代码的注释,我是一位初学者试图重写某些逻辑,例如登录后保存token的逻辑,于是我删除了某些代码,结果导致页面菜单不显示了.
我试图理解菜单生成与权限校验的逻辑,但是一脸茫然.
其次,我不理解在构建菜单时在vue中使用react的jsx语法是何用意.

**Comment by uyarn** [comment]
emmm jsx并不和react强绑定呀

**Comment by yaxnice** [comment]
好的,记得写注释[狗头]
