### ISSUE TITLE
页面显示错误

### ISSUE THREAD

**Issue by yaxnice** [Tencent/tdesign-vue-next-starter#234]
### tdesign-vue-next-starter 版本

0.3.5

### 重现步骤

在一定的页面尺寸下这里会重叠.
![图片显示错误](https://user-images.githubusercontent.com/87602183/179155641-2e8a1c90-eb23-4273-9318-c2ce1b49c32c.png)

**Comment by uyarn** [comment]
集中到https://github.com/Tencent/tdesign-vue-next-starter/issues/235 回复处理吧 都是一类样式在小尺寸的问题
