### ISSUE TITLE
页面尺寸调整样式问题

### ISSUE THREAD

**Issue by yaxnice** [Tencent/tdesign-vue-next-starter#235]
### tdesign-vue-next-starter 版本

0.3.5

### 重现步骤

在一定的页面尺寸下滑动横向滚动条,在表格固定列的右侧会出现不明物体
![表格显示异常](https://user-images.githubusercontent.com/87602183/179155938-0a1e3c6a-3d29-4ede-9054-a1bb67d5c363.png)

**Comment by yaxnice** [comment]
大概尺寸是页面放大到刚好可以让两个表格并排排放在多一点点

**Comment by yaxnice** [comment]
版本是0.3.5

**Comment by uyarn** [comment]
- [ ] https://github.com/Tencent/tdesign-vue-next-starter/issues/234

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/179160920-e1a049bb-266f-44b8-8403-0a96b6fc3f76.png)

**Comment by timi137137** [comment]
我无法重现 @uyarn 你重现了吗

**Comment by timi137137** [comment]
- [ ] #231

**Comment by uyarn** [comment]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/26377630/179161284-e5b0f760-c3a4-41b6-a17f-dd91decca749.png">
我也没复现 不过我倒是发现这个宽度下 卡片直接的距离要处理下 现在有部分是紧挨着的

**Comment by yaxnice** [comment]
大概在这个宽度
![d5ff00e45d7ba83843bc38561adbea4](https://user-images.githubusercontent.com/87602183/179161435-a3f3752a-7012-4cfb-b724-1ee87af3933f.png)

**Comment by yaxnice** [comment]
已经尝试了Edge和google浏览器,都存在这样的问题

**Comment by timi137137** [comment]
这个宽度下确实出现了这个问题，感觉是媒体查询没写好

**Comment by timi137137** [comment]
@yaxnice 0.19.0的vue-next修复了这个问题
![image](https://user-images.githubusercontent.com/36812439/182824673-431edce2-e447-48b3-971e-2557b8ccc051.png)
