### ISSUE TITLE
[图表] 改变颜色/模式 出现页面卡死等异常的问题

### ISSUE THREAD

**Issue by 4566704** [Tencent/tdesign-vue-next-starter#239]
### tdesign-vue-next-starter 版本

0.0.35

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/dashboard/base

### 重现步骤

原本是等别人反馈，2个月过去了... 每天能遇到1-2次。
先看问题：DevTools 提示 install.2aa2d2ef.js:43 Uncaught (in promise) Error: Initialize failed: invalid dom.

![image](https://user-images.githubusercontent.com/94276735/179515533-ea4fadd5-2c7d-40f7-80ed-fe9a2cadc132.png)

页面
![image](https://user-images.githubusercontent.com/94276735/179515581-c4cef991-c869-4944-862d-4c80b39c454f.png)

经过无数次试验，最终版重现步骤：

1.浏览 https://tdesign.tencent.com/starter/vue-next/
2.点击仪表盘的子菜单统计报表，再点击概览仪表盘
3.切换成暗黑模式

发现2个多月了才反馈，原因是bug很难重现，每天操作页面几百上千次，才偶尔重现1-2次

### 期望结果

能正常切换暗黑模式

### 实际结果

页面异常，卡死

### 框架版本

vue3.2.25

### 浏览器版本

Chrome/103.0.0.0

### 系统版本

Windows 10 21H2

### Node版本

v16.5.1

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/179684311-ea180f40-1014-4e26-8dc0-11d4e822367e.png)
你版本不对，现在都0.3.6了

**Comment by 4566704** [comment]
@timi137137 不是我的，是腾讯官方的演示地址，不知道怎么联系他们，让他们升级一下

**Comment by 4566704** [comment]
2个多月了，也没人反馈也没修复，这个项目没人管

**Comment by timi137137** [comment]
问题是根本不存在这个问题啊（哭笑不得）

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/179697410-9dab21fb-7887-426f-b711-faf884af3d20.png)
倒是rollup打包导致的问题一直存着

**Comment by 4566704** [comment]
2个多月了一直存在这个页面卡死问题，我自己的电脑，云服务器上都测试了

**Comment by timi137137** [comment]
哦我知道了，你是遇到了重复渲染的问题，这个正常开发下遇不到的（前提是你没用echart）
看看其他开发人员怎么看吧，最近有点忙

**Comment by 4566704** [comment]
嗯，我提交的是官方演示页面会卡死。 我自己项目也会像官方演示的一样卡死

**Comment by 4566704** [comment]
![image](https://user-images.githubusercontent.com/94276735/179698856-aac65d6f-0d84-4a3b-8d5c-a45ebc490ddb.png)
是官方的演示网页，这是在linux系统上也卡死，谷歌核心83

**Comment by timi137137** [comment]
因为dom渲染的问题所以会出现卡死，如果你不做这种切换操作应该不会有问题，记录下来了

**Comment by uyarn** [comment]
这个问题比较难处理 主要是为了换色 换色如果是正常的DOM节点 切换Token就会换色了 但是图表绘制处理的又是canvas 切换token是不会生效的 需要重新绘制 这个时候就容易出现卡死的问题

**Comment by timi137137** [comment]
done
- #254
