### ISSUE TITLE
[Breadcrumb] 面包屑导航不垂直居中，箭头导航位置不协调

### ISSUE THREAD

**Issue by gotounix** [Tencent/tdesign-vue-next-starter#240]
### tdesign-vue-next-starter 版本

0.3.6

### 期望结果

![网页捕获_18-7-2022_213721_tdesign tencent com](https://user-images.githubusercontent.com/18606632/179523767-c85b3c4a-c3a3-4ea9-85a9-b70b02da5494.jpeg)

### 实际结果

![网页捕获_18-7-2022_212817_tdesign tencent com](https://user-images.githubusercontent.com/18606632/179522531-34a75583-e023-47f4-8fd4-0fdad27a4f4c.jpeg)

### 补充说明

面包屑导航垂直居中，箭头居中，是不是会更好看些？

**Comment by timi137137** [comment]
这个我也发现了，但是不知道当初为什么要加padding， @uyarn 当初是为什么要加这个间距呢

**Comment by uyarn** [comment]
![image](https://user-images.githubusercontent.com/26377630/181186787-e153ab28-244c-4b7d-90a2-a29961f6f809.png) 
看着是全局a 标签样式影响了

**Comment by gotounix** [comment]
@uyarn @timi137137 垂直居中这个样式不改吗？

**Comment by uyarn** [comment]
@gotounix sorry只处理了一半 reopen一下。
