### ISSUE TITLE
[代码规范] 关于开发规范问题

### ISSUE THREAD

**Issue by gotounix** [Tencent/tdesign-vue-next-starter#241]
### tdesign-vue-next-starter 版本

0.3.6

### 重现步骤

文档中 [文件的命名规范](https://tdesign.tencent.com/starter/docs/vue-next/develop-rules#%E6%96%87%E4%BB%B6%E7%9A%84%E5%91%BD%E5%90%8D%E8%A7%84%E8%8C%83) 写道：

1. 文件名全部使用小写，`kebab-case` 形式命名。如 `td-layout.tsx`、 `td-header.tsx`。

2. 引导型特殊文件、样式及资源目录文件除外,如 `index.ts`、 `main.ts`、`index.vue`。

可实际项目中文件命名却很随意，例如：

[middle-chart.vue](https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/pages/dashboard/base/components/middle-chart.vue)

[CommonTable.vue](https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/pages/list/components/CommonTable.vue)

### 补充说明

可能我有强迫症……

**Comment by uyarn** [comment]
文档已由@timi137137 更新
