### ISSUE TITLE
关于build之后的dist在nginx部署后报错的问题

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next-starter#258]
### tdesign-vue-next-starter 版本

0.19

### 重现步骤

npm run build之后的dist，在nginx部署运行，在浏览的控制台有如下报错信息：
`Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`

应做如下修改：
根目录下的env文件中的` VITE_BASE_URL = ./ ` 中 "./" 应该为"/" ，即去掉 .

**Comment by timi137137** [comment]
收到，感谢反馈

**Comment by timi137137** [comment]
done 
- #259

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/183403447-3db066a5-244c-4922-9bb1-a64ec30f6e1e.png)
