### ISSUE TITLE
store 目录下面的permission 文件里面restore方法

### ISSUE THREAD

**Issue by xqh-jason** [Tencent/tdesign-vue-next-starter#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xqh-jason** [comment]
![image](https://user-images.githubusercontent.com/75606017/147813629-ea045261-d71c-4799-9780-a5f879b877cf.png)
多增加一个if (router.hasRoute(item.name)) 判断会不会好些

**Comment by pengYYYYY** [comment]
可以增加提高健壮性
