### ISSUE TITLE
[meun] 导航布局选择分割菜单后点退到登录页会空白

### ISSUE THREAD

**Issue by setli** [Tencent/tdesign-vue-next-starter#260]
### tdesign-vue-next-starter 版本

0.40

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/dashboard/base

### 重现步骤

系统设置->选择第三个布局->勾选分割菜单->点击退到登录页

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/183470990-c59feb3f-9874-471c-9538-9af72e5f5600.png)
...
我修一下，冲突了

**Comment by timi137137** [comment]
done 
- #261
