### ISSUE TITLE
[Menu] 点击两个不同菜单后再点击登录中心会空白

### ISSUE THREAD

**Issue by setli** [Tencent/tdesign-vue-next-starter#264]
### tdesign-vue-next-starter 版本

0.40

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/dashboard/base

### 重现步骤

点击不同的两个菜单后再点击登录中心会出现空白页

![image](https://user-images.githubusercontent.com/19206807/183930345-7dfaa93b-3f89-46bb-a765-a7843ca9610f.png)

![image](https://user-images.githubusercontent.com/19206807/183930505-1a93d8ea-4624-485c-beb8-9631489f0950.png)

感谢修复

**Comment by timi137137** [comment]
哇不是吧，我改炸了吗（？）对不起我待会好好看看

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/183956941-9296a213-4f21-41fb-9025-a3a41a7ac093.png)
（？）是预期效果，但是好像路由表重叠了，怪

**Comment by uyarn** [comment]
@setli  vue-router的升级带来的影响比预期的大 先按这个https://github.com/Tencent/tdesign-vue-next-starter/pull/266 revert下 等我们处理完了再发个新版本升级上去

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-next-starter/pull/251 @timi137137 是这里添加了key带来的影响

**Comment by uyarn** [comment]
@setli  实际还有这个key的改动带来的影响 https://github.com/Tencent/tdesign-vue-next-starter/pull/251 麻烦再把这个key先处理掉 我们再排查下是什么原因导致的
