### ISSUE TITLE
TD Starter 开启多标签tab的时候出现Bug

### ISSUE THREAD

**Issue by ChrisHu7** [Tencent/tdesign-vue-next-starter#265]
### tdesign-starter-cli 版本

TDesign Starter 0.4.0

### 重现链接

https://tdesign.tencent.com/starter/vue/#/list/base

### 重现步骤

设置中开启多标签tab
![WechatIMG616](https://user-images.githubusercontent.com/98387325/183854432-d0cff4b6-d993-4ef7-8240-f38504c3a3d1.jpeg)

**Comment by uyarn** [comment]
@ChrisHu7 升级vue-router带来的影响比预期的多 我们先revert掉改动 https://github.com/Tencent/tdesign-vue-next-starter/pull/266 等把问题修复我们再升级上来
