### ISSUE TITLE
[router] 升级vue-router 4.1.x 待处理问题

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue-next-starter#267]
### tdesign-vue-next-starter 版本

0.4.0

### 相关issue

- [x] 多标签Tab页影响 https://github.com/Tencent/tdesign-vue-next-starter/issues/265
- [x] 关闭多标签页过程中不符合预期地跳转到登陆页的异常

**Comment by 4566704** [comment]
vue-router 4.1.x  页面打开一片空白，也没报错。试了多个浏览器。太吓人 了。
换回 vue-router 4.0.0 就好了

**Comment by uyarn** [comment]
> vue-router 4.1.x 页面打开一片空白，也没报错。试了多个浏览器。太吓人 了。 换回 vue-router 4.0.0 就好了

似乎对keep-alive有破坏性的改动.. 我们继续处理完再升上去

**Comment by timi137137** [comment]
vue-router v4.1.5 疑似已修复问题
![image](https://user-images.githubusercontent.com/36812439/196409418-5a9c35d7-3cfb-4748-8fcf-e6c64970a64c.png)

**Comment by timi137137** [comment]
@uyarn  LGTM 你试试，如果没问题我可以提一下版本
