### ISSUE TITLE
Feature Request: 在脚手架自动生成的项目中自带light/dark mode切换按钮

### ISSUE THREAD

**Issue by pikanglong** [Tencent/tdesign-vue-next-starter#27]
在[TDesign Web Vue Next 文档](https://tdesign.tencent.com/vue-next/components/dark-mode)的右上角有一个 dark mode 的切换按钮，但是通过 tdesign-vue-next-starter 生成的项目中却没有这个按钮。希望能够在初始化的项目中添加这个组件。

**Comment by 19805185089** [comment]
啊对对对

**Comment by pengYYYYY** [comment]
在设置里面有这一块的配置
