### ISSUE TITLE
tsx部分代码改sfc以支持按需引入自动注册

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next-starter#275]
### tdesign-vue-next-starter 版本

0.4.1

### 这个功能解决了什么问题

tsx部分代码改sfc以支持按需引入自动注册
项目中存在一些组件是用jsx写的 对于部分用户来说存在一定的理解成本 期望整个项目的组件都改为使用vue sfc编写 主要是layouts中的部分代码
<img width="336" alt="image" src="https://user-images.githubusercontent.com/26377630/183397515-3709403b-841e-4930-b1a0-66eac2e2039f.png">

### 你建议的方案是什么

整个项目的组件都改为使用jsx编写的代码改为vue sfc编写

**Comment by zhangpaopao0609** [comment]
走起
