### ISSUE TITLE
[多标签页] 支持非当前打开的标签页右键操作

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue-next-starter#277]
### 这个功能解决了什么问题

 目前实现的多标签页只支持打开的标签页右键操作 根据反馈 需要修改成支持所有标签页都允许右键操作
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/26377630/187656964-05506510-d430-4c9f-8a3e-4f3ed3bcf00e.png">

### 你建议的方案是什么

修改代码 改成支持所有标签页都允许右键操作

**Comment by zhangpaopao0609** [comment]
走起

**Comment by PDieE** [comment]
> 走起

你已经在改了么？
