### ISSUE TITLE
[导航布局] “设置”面板当中的“导航布局”设置为顶部显示菜单无效

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next-starter#290]
### tdesign-vue-next-starter 版本

0.4.1

### 重现步骤

在“refactor: 将layout代码转成sfc”这次提交之后的最新版本，“设置”面板当中的“导航布局”设置为顶部显示菜单无效，header部分不会现实菜单。如下图： 
![1](https://user-images.githubusercontent.com/4152089/188342126-b7faab72-e894-4cdb-beed-008e539fbbfd.png)

**Comment by timi137137** [comment]
fix for #292
