### ISSUE TITLE
切换主题是跟随系统菜单栏无法更换配色

### ISSUE THREAD

**Issue by baozoulolw** [Tencent/tdesign-vue-next-starter#312]
### tdesign-vue-next-starter 版本

0.5.1

### 重现步骤

在切换主题时发现选择跟随系统，左边menu菜单栏主题无法更换，最后发现是 l-side-nav组件在读取theme时采用的是直接读取mode而不是采用 getters 的displayMode方法，故导致读取的mode为auto，所以t-menu组件无法识别theme为 auto的值
出现bug代码：
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/31173826/190595112-7643875c-228c-4c3d-9de1-ac510b7a49d3.png">
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/31173826/190595541-adfb278e-3a7d-494e-9014-65641a4a8957.png">

修改为 
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/31173826/190595208-56b1e793-f1d6-4944-a454-1ae2c787e0c2.png">
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/31173826/190595688-69cb3ba5-a6b4-4e66-9cef-8e5c8d4da252.png">

即可正确切换主题

### 期望结果

正确切换主题

### 实际结果

左边菜单栏无法切换系统更随主题

**Comment by timi137137** [comment]
对不起这是我们的疏忽
原本确实是`displayMode`的
![image](https://user-images.githubusercontent.com/36812439/190656054-148a3d3a-79a5-4536-8563-9b2e011b0db3.png)
非常抱歉给你带来不好的体验了现在就改

**Comment by timi137137** [comment]
fix for #315
