### ISSUE TITLE
[登录页] 首次登录发生死循环，RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by anyths** [Tencent/tdesign-vue-next-starter#313]
### tdesign-vue-next-starter 版本

0.5.1

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/login?redirect=/dashboard/base

### 重现步骤

必须用从未打开过starter项目页的浏览器，可清理缓存或者用隐私模式
链接需直接用 登录页 的链接。
 
1. 使用浏览器第一次打开 官方预览项目的登录页；
2. 点击登录
3. 弹出 “登录成功”提示，同时也 报错 Maximum call stack size exceeded
4. 路由未跳转，重复依旧上述现场

### 期望结果

直接登录成功

### 实际结果

登录失败
<img width="428" alt="Screenshot 2022-09-16 200352" src="https://user-images.githubusercontent.com/37953578/190634843-178889bf-15d0-4e5e-9ed1-1242d6dd229d.png">

### 浏览器版本

Microsoft Edge Version 105.0.1343.33 (Official build) (64-bit)

### 系统版本

Windows 11 Pro 21H2 22000.856

### 补充说明

首次登录发生此问题。后续可通过刷新就可以越过此问题。

**Comment by timi137137** [comment]
因为持久化后导致第一次加载本地不存在信息出现的循环调用问题，正在修复

**Comment by timi137137** [comment]
fix for #314
