### ISSUE TITLE
[router]  菜单跳转时被动画阻塞，导致即使很简单的页面切换都要接近一秒

### ISSUE THREAD

**Issue by Colin-XKL** [Tencent/tdesign-vue-next-starter#320]
### tdesign-vue-next-starter 版本

0.5.0 

### 重现链接

官网的菜单也有同样的问题 https://tdesign.tencent.com/starter/vue-next/#/list/card

### 重现步骤

点击菜单->菜单点击动画播放->载入新页面  

这个步骤似乎是阻塞的，菜单动画播放完了才开始加载新页面，我在本地调试，很简单的 hello world 页面，切换都要接近一秒，所有页面都有这个问题。

**Comment by timi137137** [comment]
（思考）你能录屏吗，我这边没发现你说的问题，谢谢

**Comment by timi137137** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/2d42a0d3-081b-4585-9e1a-33310470f868)
重新抓包测试了一下，似乎动画太多了。暂时无解

**Comment by timi137137** [comment]
确认问题来自 Vuejs 官方，问题来自于`transition`标签。
暂时解决方法：
将 `src/layouts/components/Content.vue` 中的代码从：
```ts
<router-view v-if="!isRefreshing" v-slot="{ Component }">
    <transition name="fade">
      <keep-alive :include="aliveViews">
        <component :is="Component" />
      </keep-alive>
    </transition>
  </router-view>
```
修改为
```ts
<router-view v-if="!isRefreshing" v-slot="{ Component }">
    <!-- <transition name="fade"> -->
      <keep-alive :include="aliveViews">
        <component :is="Component" />
      </keep-alive>
    <!-- </transition> -->
  </router-view>
```

即可暂时解决

> 另一个办法是为标签添加mode属性，但会导致有长时间白屏故此不采用
