### ISSUE TITLE
怎么支持js语法，部署后引入js文件，js文件内容报红线。  使用的vscode，发现兼容ts语法就不兼容js语法[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next-starter#321]
### tdesign-vue-next-starter 版本

怎么支持js语法，部署后引入js文件，js文件内容报红线。  使用的vscode，发现兼容ts语法就不兼容js语法

### 重现步骤

![image](https://user-images.githubusercontent.com/19531939/192419457-7d3f86b4-4efe-4a73-8ee6-2440c89fc699.png)

### 系统版本

window10

### Node版本

16.6

**Comment by timi137137** [comment]
非常抱歉，为了更好的使用体验我们不打算支持js，ts的类型约束能让代码更好的运行，您可以尝试多试试ts语法
