### ISSUE TITLE
编译组件时候报错umd编译不出来

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next-starter#323]
### tdesign-vue-next-starter 版本

0.52

### 重现步骤

![image](https://user-images.githubusercontent.com/19531939/192925101-e815f692-14e6-43ff-bdb3-0d4aad53864d.png)

vite.config.js配置内容：
import { ConfigEnv, UserConfig, loadEnv } from 'vite';
import { viteMockServe } from 'vite-plugin-mock';
import createVuePlugin from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import svgLoader from 'vite-svg-loader';

import path from 'path';

const CWD = process.cwd();

// https://vitejs.dev/config/
export default ({ mode }: ConfigEnv): UserConfig => {
  const { VITE_BASE_URL } = loadEnv(mode, CWD);
  return {
    base: VITE_BASE_URL,
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },

    plugins: [
      createVuePlugin(),
      vueJsx(),
      viteMockServe({
        mockPath: 'mock',
        localEnabled: true,
      }),
      svgLoader(),
    ],
    build: {
      outDir: 'process-design',
      lib: {
        entry: path.resolve(__dirname, './src/components/flow/index.ts'),
        name: 'ProcessDesign',
        fileName: 'ProcessDesign',
        // fileName: (format) => `process-builder.${format}.js`,
        formats: ['umd'], // 默认['es', 'umd']
      },
      rollupOptions: {
        external: ['vue'],
        output: {
          inlineDynamicImports: true, 
          globals: {
            vue: 'Vue',
          },
           format: 'umd', // 默认'es'
        },
      },
    },

    server: {
      port: 3002,
      host: '0.0.0.0',
      proxy: {
        '/api': 'http://127.0.0.1:3000/',
      },
    },
  };
};

package.json配置内容：
{
  "name": "process-design",
  "private":false,
  "description": "process-design-v0.1.0",
  "files":["process-design"],
  "main": "process-design/process-builder.umd.js",
  "module": "process-design/process-builder.es.js",
  "version": "0.1.0",
  "license": "MIT",
  "keywords": [
    "vue",
    "process-design"
  ],
  "author": "hy",
  "exports": {
		".": {
			"import": "./process-design/process-builder.es.js",
      "require": "./process-design/process-builder.umd.js"
		}
	},
  "scripts": {
    "dev:mock": "vite --open --mode mock",
    "dev": "vite --open --mode development",
    "dev:linux": "vite --mode development",
    "build:test": "vite build --mode test",
    "build": "vue-tsc --noEmit && vite build --mode release",
    "preview": "vite preview",
    "lint": "eslint --ext .vue,.js,.jsx,.ts,.tsx ./ --max-warnings 0",
    "lint:fix": "eslint --ext .vue,.js,jsx,.ts,.tsx ./ --max-warnings 0 --fix",
    "stylelint": "stylelint src/**/*.{html,vue,sass,less}",
    "stylelint:fix": "stylelint --fix src/**/*.{html,vue,vss,sass,less}",
    "site:preview": "npm run build && cp -r dist _site",
    "test": "echo \"no test specified,work in process\"",
    "test:coverage": "echo \"no test:coverage specified,work in process\""
  },
  "dependencies": {
    "@antv/layout": "^0.3.0",
    "@antv/x6": "^1.34.1",
    "axios": "^0.27.2",
    "dayjs": "^1.10.6",
    "echarts": "~5.1.2",
    "insert-css": "^2.0.0",
    "js-beautify": "^1.14.0",
    "lodash": "^4.17.21",
    "md5": "^2.3.0",
    "nprogress": "^0.2.0",
    "pinia": "^2.0.11",
    "pinia-plugin-persistedstate": "^2.1.1",
    "qrcode.vue": "^3.2.2",
    "qs": "^6.10.5",
    "sass": "^1.55.0",
    "tdesign-icons-vue-next": "^0.1.1",
    "tdesign-vue-next": "0.20.3",
    "tvision-color": "^1.3.1",
    "vue": "^3.2.31",
    "vue-clipboard3": "^2.0.0",
    "vue-router": "~4.0.11"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.0.3",
    "@commitlint/config-conventional": "^17.0.3",
    "@types/echarts": "^4.9.10",
    "@types/lodash": "^4.14.182",
    "@types/qs": "^6.9.7",
    "@types/ws": "^8.2.2",
    "@typescript-eslint/eslint-plugin": "^4.29.3",
    "@typescript-eslint/parser": "^4.29.3",
    "@vitejs/plugin-vue": "^2.3.1",
    "@vitejs/plugin-vue-jsx": "^1.1.7",
    "@vue/compiler-sfc": "^3.0.5",
    "@vue/eslint-config-typescript": "^11.0.0",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^7.32.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-vue": "^9.2.0",
    "eslint-plugin-vue-scoped-css": "^2.2.0",
    "less": "^4.1.1",
    "lint-staged": "^12.1.2",
    "mockjs": "^1.1.0",
    "prettier": "^2.4.1",
    "stylelint": "~13.13.1",
    "stylelint-config-prettier": "~9.0.3",
    "stylelint-less": "1.0.1",
    "stylelint-order": "~4.1.0",
    "typescript": "~4.7.4",
    "vite": "^2.7.1",
    "vite-plugin-mock": "^2.9.6",
    "vite-svg-loader": "^3.1.0",
    "vue-tsc": "^0.35.0"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "lint-staged": {
    "*.{js,jsx,vue,ts,tsx}": [
      "prettier --write",
      "npm run lint:fix",
      "git add ."
    ],
    "*.{html,vue,vss,sass,less}": [
      "npm run stylelint:fix",
      "git add ."
    ]
  }
}

这是我写的导出组件：运行是没问题，可以正常执行
![image](https://user-images.githubusercontent.com/19531939/192925333-76f90f31-5ba2-468c-bb0e-0dedf50d5980.png)

### 期望结果

期望编译组件生成umd，es这两个js文件

### Node版本

16

**Comment by timi137137** [comment]
没懂，你为什么编译vue-next会在vue-next-starter里面发issue（思考）

**Comment by uyarn** [comment]
图一字面意思 calc里面的内容运算符和必须有withespace隔开
后面的umd问题以及其他编译问题不是该项目相关的问题 可以到vite的文档/仓库找答案
https://cn.vitejs.dev/guide/
