### ISSUE TITLE
基于tdesign封装的组件打包后在本地tdesign项目中用npm安装使用报错

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next-starter#324]
### tdesign-vue-next-starter 版本

0.52

### 重现步骤

![image](https://user-images.githubusercontent.com/19531939/192932465-8e83e2c0-392b-4757-83eb-c7a7c7a85532.png)
组件运行没问题，但是引入到其他的tdesign项目中shi使用时候，就是报这个错误。
我该从哪里去修复。

### 期望结果

我该从哪里去修复。

### Node版本

16

**Comment by uyarn** [comment]
ProcessDesign是啥..

**Comment by huyiwill** [comment]
> ProcessDesign这个是封装的组件。准备放到其他项目中去使用

**Comment by uyarn** [comment]
封装了TDesign吗？

**Comment by timi137137** [comment]
你导入这个的时候store还没初始化，估计是这个问题

**Comment by huyiwill** [comment]
是不是我导出组件install时候，要把依赖的三方插件也一起install，然后再进行导出



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月29日 14:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Tencent/tdesign-vue-next-starter] 基于tdesign封装的组件打包后在本地tdesign项目中用npm安装使用报错 (Issue #324) |

你导入这个的时候store还没初始化，估计是这个问题

**Comment by huyiwill** [comment]
ProcessDesign是封装的组件。其他项目用这个组件时候报错



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月29日 11:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [Tencent/tdesign-vue-next-starter] 基于tdesign封装的组件打包后在本地tdesign项目中用npm安装使用报错 (Issue #324) |

ProcessDesign是啥..
