### ISSUE TITLE
访问编译成功后项目报错"host" can  not read

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next-starter#325]
### tdesign-vue-next-starter 版本

0.52

### 重现步骤

index.9e9cb2f9.js:3763 Uncaught TypeError: Cannot read properties of undefined (reading 'host')
    at index.9e9cb2f9.js:3763:21808
![image](https://user-images.githubusercontent.com/19531939/193170553-4b728acc-ef09-4f62-b422-3cb5cd3c1a3a.png)
直接访问项目就出现空白页面。项目本地运行是正常的。就是编译后访问报错，找不到原因，头大。
项目的main.ts中引入了写的封装组件

### 实际结果

正常访问编译后的项目

### Node版本

16

**Comment by timi137137** [comment]
你是不是改了编译选项，这是请求工具报的错

**Comment by huyiwill** [comment]
> 你是不是改了编译选项，这是请求工具报的错

这个是vite.config.js配置，没有修改编译选项
![企业微信截图_16645033139860](https://user-images.githubusercontent.com/19531939/193174178-98d21f11-ce63-4f61-ba85-cc6d8e8ccb7c.png)

**Comment by timi137137** [comment]
你的依赖确定装好了吗(?

**Comment by huyiwill** [comment]
> 你的依赖确定装好了吗(?
大神，方便加下微信吗
项目在本地可以正常npm run dev的。就是编译后部署访问报错。 依赖都安装了
![image](https://user-images.githubusercontent.com/19531939/193174855-96d641b9-7bd3-41d1-96da-953249b815e3.png)

**Comment by huyiwill** [comment]
> 你的依赖确定装好了吗(?

能帮忙看下什么原因吗

**Comment by timi137137** [comment]
没法复现，有步骤之类的吗（思考）
