### ISSUE TITLE
@/style/variables是否应该在vite中设置为less全局变量

### ISSUE THREAD

**Issue by dianjie** [Tencent/tdesign-vue-next-starter#326]
### 这个功能解决了什么问题

不用重复性引入`@import '@/style/variables';`

### 你建议的方案是什么

在vite配置中加，然后把相关`@import '@/style/variables';`清除么。
```
css: {
  preprocessorOptions: {
    less: {
      javascriptEnabled: true,
      additionalData: `@import "${path.resolve(__dirname, 'src/style/variables.less')}";`,
    },
  },
},
```

**Comment by timi137137** [comment]
不应该，因为其实整个项目引入的次数就两次，不必设置为全局变量

**Comment by dianjie** [comment]
@timi137137 好比如在vue style里面，要用到starter-prefix变量，不引入variables，会报错的呐。

**Comment by timi137137** [comment]
@uyarn 你看看吧，我没用到css token

**Comment by uyarn** [comment]
sounds good 可以提个PR来改下

**Comment by uyarn** [comment]
> @uyarn 我尝试通过ESM产物引入组件库，然后想细致化主题定制，会报错！
> 
> ```
> import TDesign from "tdesign-vue-next/esm";
> import "tdesign-vue-next/esm/style/index.js";
> ```

报什么错？

**Comment by dianjie** [comment]
> > @uyarn 我尝试通过ESM产物引入组件库，然后想细致化主题定制，会报错！
> > ```
> > import TDesign from "tdesign-vue-next/esm";
> > import "tdesign-vue-next/esm/style/index.js";
> > ```
> 
> 报什么错？

less语法问题！
