### ISSUE TITLE
下载模板失败：Service Temporarily Unavailable

### ISSUE THREAD

**Issue by CharlesGC** [Tencent/tdesign-vue-next-starter#33]
**Describe Environment**
node -v
v14.18.1
npm -v
6.14.15

**Describe the bug**
使用官网td-starter in 初始化项目时，提示下载模板失败
✖ ❗错误：下载模板失败
❗错误信息： HTTPError: Response code 503 
(Service Temporarily Unavailable)  

**Additional context**

**Comment by uyarn** [comment]
有反馈过可能是网络问题 麻烦再尝试一下

**Comment by pikanglong** [comment]
可能是git通过SSH下载时，本机没有SSH-key。

尝试在本机git bash执行命令：

```
ssh-keygen -t rsa -C "youremail@example.com"
```

**Comment by uyarn** [comment]
`npm install tdesign-starter-cli@latest-g` 新版本改善了这个问题 如果还有问题可以reopen it
