### ISSUE TITLE
[Dropdown] tdesign-vue-nex升级到2.4.0之后的版本，由于最新版本Dropdown的改变，导致本项目启动后一片空白

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next-starter#334]
### tdesign-vue-next-starter 版本

0.5.2

### 重现步骤

tdesign-vue-nex升级到2.4.0或2.4.1版本，由于最新版本tdesign-vue-nex中Dropdown组件的改变，导致本项目启动后一片空白。

**Comment by uyarn** [comment]
@chnykn 麻烦先使用下@0.24.2-alpha.1 有个v-if的缺陷导致的

**Comment by chnykn** [comment]
@uyarn 谢谢你

**Comment by uyarn** [comment]
@chnykn  0.24.2已发布 可以升级使用
