### ISSUE TITLE
[permission] 当某个用户没有某个路由权限时会出现Maximum call stack size exceeded

### ISSUE THREAD

**Issue by piupuer** [Tencent/tdesign-vue-next-starter#337]
### tdesign-vue-next-starter 版本

^0.24.1

### 重现步骤

1.假设有3个页面/list/base, /list/card, /list/filter
2.登陆成功后router.push('/list/base')
3. admin账户有全部页面权限，所有页面都可以打开
4. test账户设置只有/list/base权限，登陆后输入/list/card

### 期望结果

正常访问

### 实际结果

Uncaught RangeError: Maximum call stack size exceeded
<img width="600" alt="image" src="https://user-images.githubusercontent.com/27284001/196106569-76440a78-025c-480d-a09a-97f2326ff3a7.png">

### 补充说明

关闭cookie功能
tdesign版本0.5.2，另外最新开发分支代码我也试了，一样存在这个问题

**Comment by timi137137** [comment]
权限系统目前在大改，你可以修改一下src/permission.ts中的逻辑暂时修复，感谢谅解

**Comment by MT-smile** [comment]
匹配/list/card时路由不存在，会匹配到路由/:w+，会重定向到/result/404，但/result/404路由在filterPermissionsRouters方法中被过滤了，导致没匹配到相应路由。
可以在router/index.ts修改路由信息
`{
    path: '/:w+',
    name: '404Page',
    component: () => import('@/pages/result/404/index.vue'),
  }`

**Comment by piupuer** [comment]
> 匹配/list/card时路由不存在，会匹配到路由/:w+，会重定向到/result/404，但/result/404路由在filterPermissionsRouters方法中被过滤了，导致没匹配到相应路由。 可以在router/index.ts修改路由信息 `{ path: '/:w+', name: '404Page', component: () => import('@/pages/result/404/index.vue'), }`

谢谢回复，感觉这样做可以解决问题，但不优雅，我等官方的改进方案吧
