### ISSUE TITLE
[Menu] 菜单样式样式问题

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next-starter#340]
### tdesign-vue-next-starter 版本

0.5.3

### 重现步骤

![image](https://user-images.githubusercontent.com/36812439/196405377-d07f7f7d-abf8-47fa-8af7-ac38d5281274.png)
![image](https://user-images.githubusercontent.com/36812439/196405416-c2bc8f6d-bfb8-4ed1-842f-5f707d7e7293.png)
![image](https://user-images.githubusercontent.com/36812439/196405723-b319140c-b35d-4793-a5bd-8973bb1845ed.png)

**Comment by evanlong0926** [comment]
我还发现一个问题：

**Comment by evanlong0926** [comment]
我还发现一个问题：
进入页面时左侧的下拉菜单，它的整体可以左右拽动

**Comment by timi137137** [comment]
> 我还发现一个问题： 进入页面时左侧的下拉菜单，它的整体可以左右拽动

我感觉是组件库的问题，但是组件库没人处理。我也没办法
