### ISSUE TITLE
浏览器访问服务器响应头返回Content-Type: text/plain; charset=utf-8，浏览器阻止访问

### ISSUE THREAD

**Issue by barryzxy** [Tencent/tdesign-vue-next-starter#35]
**Describe Environment**
windows10 
Add browser version here
edge浏览器
**Describe the bug**
这边用gin框架搭的服务器，用tdesing-vue-next-starter生成的前端代码，通过gin代理访问
gin代码：

```go
func main() {
	r := gin.Default()
	r.Static("/", "./dist")
	r.Run()
}
```

部分电脑访问响应头返回：Content-Type: text/plain; charset=utf-8
部分电脑访问响应头返回：Content-Type: text/javascript; charset=utf-8
当返回事text/plain时浏览器阻止访问。
**Additional context**

**Comment by barryzxy** [comment]
![image-20220103093417814](https://user-images.githubusercontent.com/5548126/148064302-c7d49b3f-30dc-4acf-91ac-5a3f0a3a00a4.png)
![image-20220103093352742](https://user-images.githubusercontent.com/5548126/148064330-e001fa88-52d9-4182-897e-242ba5b03c42.png)

![Uploading 34d4829f1e31429737d9c93acc21206.png…]()

**Comment by uyarn** [comment]
统一在 https://github.com/Tencent/tdesign-vue-next-starter/issues/34 处理 此issue先close
