### ISSUE TITLE
[权限相关] 非roles: ['all']的情况下 会出现paths should start with a "/": "add" should be "/add".

### ISSUE THREAD

**Issue by PAINCLOWN** [Tencent/tdesign-vue-next-starter#352]
### tdesign-vue-next-starter 版本

tdesign-starter-cli@0.3.2 "tdesign-vue-next": "^0.24.5"

### 重现步骤

非roles: ['all']的情况下会进行路由过滤filterPermissionsRouters，这个时候退出到登录页会报错Route paths should start with a "/": "detail" should be "/detail"
![image](https://user-images.githubusercontent.com/29433774/199418822-30151564-9f51-4684-a21f-e5bb415bee4d.png)

### 期望结果

['all'] 与非['all'] 正常

### 实际结果

['all']放弃这种写法 如果需要所有权限 []中填写所有路由字段，这是目前我的解决方案，但是如果路由过多 会非常繁琐

**Comment by chenyuncai** [comment]
应该跟权限配置无关，是动态添加路由时，之前根据权限过滤出的removeRoutes是二级路由配置，而restore重置路由时addRoutes当成一级路由添加了，可能正确的做法是在收集removeRoutes时保留parentRouteName信息，重置路由时，使用

```
router.addRoute(parentRouteName, childRoute);
```
