### ISSUE TITLE
[header] 升级0.24.8之后header右侧内容位置跑偏了

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next-starter#363]
### 重现链接
https://tdesign.tencent.com/starter/vue-next/#/dashboard/base

### 重现步骤
升级tdesign-vue-next至0.24.8

### 期望结果
样式不变

### 实际结果
升级之后starter顶部header右侧的按钮和图标跑到了左边
![image](https://user-images.githubusercontent.com/20508822/203494308-7a6fe60d-ca22-4e26-b572-6e89db869a81.png)

| Environment | Info |
|---|---|
| 相关版本 | - |
| 框架版本 / 基础库版本 | Vue(3.2.31) |
| 系统、浏览器 | MacOS(12), Chrome(107) |
| Node版本 |  |

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/203695983-7e81dc06-939e-4c51-b979-3da97db6bc3c.png)
![image](https://user-images.githubusercontent.com/36812439/203696042-f40d7837-5730-4a1b-ba77-54669c5c1425.png)
![image](https://user-images.githubusercontent.com/36812439/203696076-5cb9bc07-02d6-469c-a2c6-e6743fdac05f.png)

有具体复现步骤吗

**Comment by wandoupeas** [comment]
直接clone官方仓库，然后将tdesign-vue-next的版本从0.24.7升级到0.24.8 启动项目 访问就是这样了

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/203706197-6fee21c4-6d67-4113-9458-1a03d436a543.png)
![image](https://user-images.githubusercontent.com/36812439/203706212-74b57b2b-18d4-4be1-9241-438a1e29a755.png)
真没发现

**Comment by wandoupeas** [comment]
有点不大理解为啥`pnpm`安装依赖就会错位呢，`npm`就没问题

**Comment by uyarn** [comment]
头部的问题可以参考 #365 改动一下 另一个问题我也没复现

**Comment by wandoupeas** [comment]
> 头部的问题可以参考 #365 改动一下 另一个问题我也没复现

另外一个问题，现在没有了，估计是pnpm的问题
