### ISSUE TITLE
[permission] 加了 permission 示例后，VITE_BASE_URL 配置目录无效，自动跳转为 /

### ISSUE THREAD

**Issue by dodu2014** [Tencent/tdesign-vue-next-starter#398]
### tdesign-vue-next-starter 版本

0.7.0

### 重现步骤

修改 .env 中 VITE_BASE_URL = /test/
dev 运行是正常的，启动后，会自动跳转到 / 目录下

vite 运行情况：
![image](https://user-images.githubusercontent.com/15245544/213959592-4b9ecdd4-f4b3-495a-bf94-6627466318e7.png)

打开后会自动跳转：
![image](https://user-images.githubusercontent.com/15245544/213959668-09b97515-5229-4551-9108-4a5da1ab7af8.png)

### 期望结果

保留 VITE_BASE_URL 配置

### 框架版本

3.2.45

### 浏览器版本

edge 109

### 系统版本

win11

### Node版本

14.18.2

**Comment by whitexie** [comment]
新年好，需要调整下`src/router/index.ts`，将`createWebHistory`的参数换成`import.meta.env.VITE_BASE_URL` 即可
```js
const router = createRouter({
  history: createWebHistory(import.meta.env.VITE_BASE_URL),
  routes: allRoutes,
  scrollBehavior() {
    return {
      el: '#app',
      top: 0,
      behavior: 'smooth',
    };
  },
});
```

**Comment by uyarn** [comment]
close as completed
