### ISSUE TITLE
需要Tab多页签支持👍

### ISSUE THREAD

**Issue by captree** [Tencent/tdesign-vue-next-starter#40]
当我听说tdesign-starter，第一时间下载试用，感觉还不错，但遗憾的发现，不支持多tab页面切换
这是一种非常符合国人操作习惯的模式，希望尽快安排上
类似解决方案：https://github.com/noahlam/vue-multi-tab
预览：https://noahlam.github.io/vue-multi-tab/

**Comment by DOUBLE-DENG** [comment]
你好，感谢您的反馈，有示例很清晰。Tab多页签呼声蛮高，开发和设计同学我们速速安排上

**Comment by captree** [comment]
> 你好，感谢您的反馈，有示例很清晰。Tab多页签呼声蛮高，我们开发和设计同学速速安排上

赞！
顺便说一下，别忘了keep-alive，如果能加入标签栏右击弹出菜单（关闭左侧，关闭右侧，关闭其他，刷新本页），就更好了

**Comment by pengYYYYY** [comment]
> > 你好，感谢您的反馈，有示例很清晰。Tab多页签呼声蛮高，我们开发和设计同学速速安排上
> 
> 赞！ 顺便说一下，别忘了keep-alive，如果能加入标签栏右击弹出菜单（关闭左侧，关闭右侧，关闭其他，刷新本页），就更好了

好的

**Comment by captree** [comment]
> 这个 Issue 被标记为了过时 stale ，因为它已经 open 了 30 天，没有任何活动。删除 stale 标签或评论，否则将在 7 天内关闭。

+1

**Comment by captree** [comment]
+1

**Comment by captree** [comment]
> 这个 Issue 被标记为了过时 stale ，因为它已经 open 了 30 天，没有任何活动。删除 stale 标签或评论，否则将在 7 天内关闭。

支愣起来 +1

**Comment by pengYYYYY** [comment]
多标签的功能需要跟随整体的迭代版本，需要等等

**Comment by xindiyang** [comment]
有没有那种情况呢，一个路由多开两次或者两次以上呢，这个如果做出来还是不错的呢

**Comment by wmhost** [comment]
1

**Comment by uyarn** [comment]
> 有没有那种情况呢，一个路由多开两次或者两次以上呢，这个如果做出来还是不错的呢

这是什么场景？

**Comment by uyarn** [comment]
已新增
