### ISSUE TITLE
layouts的MenuContent.vue文件修改

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next-starter#401]
https://github.com/Tencent/tdesign-vue-next-starter/blob/5b8ca6ec4b62d93e4d07845d34902a9fffbd74b2/src/layouts/components/MenuContent.vue#L20

这行代码应增加 class="t-icon" ，既如下：
`<component :is="menuIcon(item)" class="t-icon"></component>`

第7、13行也要同样修改。

不然会导致import的svg图标显示不正常。

**Comment by timi137137** [comment]
草，忘了这茬了非常抱歉

**Comment by chnykn** [comment]
@timi137137 你现在这样修改是不行的。对于t-icon是ok的，但是对于import的svg还是不正常。

**Comment by uyarn** [comment]
或者layout.less 可以加 . t-default-menu .t-menu__item svg  { width: 20px, height: 20px; } 影响所有svg图标
