### ISSUE TITLE
[src\layouts\components\MenuContent.vue] 潜在的性能问题

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next-starter#412]
### tdesign-vue-next-starter 版本

0.7.0

### 重现步骤

src\layouts\components\MenuContent.vue 文件当中的 getMenuList 函数，递归转换了全部MenuRoute为ListItemType；

MenuContent.vue内只会用到两个层级的ListItemType（当前及其children）；

MenuContent.vue内会继续递归调用MenuContent.vue这个组件 `<menu-content v-if="item.children" :nav-data="item.children" />`，这样导致MenuContent.vue递归调用MenuContent.vue的时候，其中的getMenuList 会重复的转换曾经转换过的MenuRoute。

如果只存在两级菜单，不会出现性能问题；如果超过两级，则有性能上的浪费。

-----------
解决方式可以有两种：
1、getMenuList 的MenuRoute转ListItemType放置到MenuContent.vue 之外、通过属性传数据进来；
2、MenuContent.vue当中，只转换用到的两个层级的MenuRoute。

**Comment by timi137137** [comment]
在文档中其实明确指出了菜单层级限制，如果出现性能损耗其实更建议梳理业务场景，判断层级是否合理
![image](https://user-images.githubusercontent.com/36812439/217450646-5ee09c4f-52ad-4187-9047-da606b31903e.png)
但是这个优化是对的，这边会研究并做出优化

**Comment by chnykn** [comment]
嗯，实际上大部分情况两级菜单足矣，所以也称不上是Bug。只是单纯从理论上，存在提到的性能问题。

**Comment by timi137137** [comment]
我麻了，你说的问题出现了
link #441

**Comment by ngyyuusora** [comment]
> 
https://github.com/Tencent/tdesign-vue-next-starter/issues/444
不好意思提一个和本issue无关的路由菜单问题，请您帮忙看一下。发现可能在一些情况下，菜单项高亮会重复。
