### ISSUE TITLE
版本如何更新

### ISSUE THREAD

**Issue by hexu2016** [Tencent/tdesign-vue-next-starter#416]
### 这个功能解决了什么问题

去年6月份的版本做了一个项目,现在能更新到现在的最新版本吗?然后依赖的tdesign-vue-next可以单独升级版本吗?

### 你建议的方案是什么

版本如何更新

**Comment by uyarn** [comment]
https://tdesign.tencent.com/starter/docs/vue-next/feedback 参考这里 页面模板其实就是业务代码 目前没有其他方式更新 只能手动对比
