### ISSUE TITLE
[后端权限] 动态生成的菜单会报错

### ISSUE THREAD

**Issue by NetFreeOps** [Tencent/tdesign-vue-next-starter#417]
### tdesign-vue-next-starter 版本

0.7.0

### 重现链接

无

### 重现步骤

`{"statusCode":200,"data":[{"path":"/admin","name":"admin","component":"LAYOUT","redirect":null,"meta":{"title":"权限管理","icon":"fork","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[{"path":"/admin/group","name":"admin-group","component":"/admin/group/index","redirect":null,"meta":{"title":"部门管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/admin/role","name":"admin-role","component":"/admin/role/index","redirect":null,"meta":{"title":"角色管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/admin/user","name":"admin-user","component":"/admin/user/index","redirect":null,"meta":{"title":"用户管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/admin/menu","name":"admin-menu","component":"/admin/menu/index","redirect":null,"meta":{"title":"菜单管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]}]},{"path":"/system","name":"system","component":"LAYOUT","redirect":null,"meta":{"title":"系统管理","icon":"server","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[{"path":"/system/config","name":"system-config","component":"/system/config/index","redirect":null,"meta":{"title":"配置管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/system/job","name":"system-job","component":"/system/job/index","redirect":null,"meta":{"title":"定时任务","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/system/log","name":"system-log","component":"/system/log/index","redirect":null,"meta":{"title":"日志管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/system/onlineUser","name":"system-onlineUser","component":"/system/onlineUser/index","redirect":null,"meta":{"title":"在线用户","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/system/notice","name":"system-notice","component":"/system/notice/index","redirect":null,"meta":{"title":"通知管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/system/dict","name":"system-dict","component":"/system/dict/index","redirect":null,"meta":{"title":"字典管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]},{"path":"/system/file","name":"system-file","component":"/system/file/index","redirect":null,"meta":{"title":"文件管理","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[]}]},{"path":"/test","name":"duojiceshi","component":"LAYOUT","redirect":null,"meta":{"title":"多级路由测试","icon":"loading","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[{"path":"layouts","name":"erjiwenjianjia","component":"LAYOUT","redirect":null,"meta":{"title":"二级文件夹","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":[{"path":"http://www.baidu.com","name":"sanjicaidan","component":"http://www.baidu.com/index","redirect":null,"meta":{"title":"三级菜单","icon":"","expnaded":null,"orderNo":0,"hidden":null,"hiddenBreadcrumb":null,"single":null},"children":null}]}]}],"succeeded":true,"errors":null,"extras":null,"timestamp":1675924050}`
后端返回如上菜单数据，对应文件存在，前端动态生成路由也正常，但是点击的时候报错Uncaught (in promise) TypeError: Failed to fetch dynamically imported module

### 期望结果

正常生成路由

### 实际结果

报错Uncaught (in promise) TypeError: Failed to fetch dynamically imported module

### Node版本

18.13.0

**Comment by uyarn** [comment]
页面文件问题 还有问题再reopen哈

**Comment by NetFreeOps** [comment]
感谢大佬

**Comment by NetFreeOps** [comment]
希望官方能出个升级工具，手动升级心累啊
