### ISSUE TITLE
[Table] 表格的滚动条可能存在bug

### ISSUE THREAD

**Issue by MillionMindFU** [Tencent/tdesign-vue-next-starter#418]
### tdesign-vue-next-starter 版本

0.7.0

### 重现链接

No response

### 重现步骤

表格在添加了bordered属性，显示边框后。
如果mock的数据大于三条，会显示出这个奇怪的横杠。
![ed9d34a856312893da3d1199714b3b2](https://user-images.githubusercontent.com/50786822/217489352-13e7a761-74d4-46a1-b760-0053f9657b30.png)
然而当mock的数据小于等于3条时，则正常。
![ae453a8e8d626c291d1e45b30b6e53b](https://user-images.githubusercontent.com/50786822/217489504-35df47ba-bc6c-49ec-91b9-4ef8baae1b61.png)

### 期望结果

不管表格获取多少数据，都能如预期显示。

### 实际结果

No response

### 框架版本

Vue(3.2.45)

### 浏览器版本

Edge(109.0.1518.78)

### 系统版本

No response

### Node版本

No response

### 补充说明

No response

**Comment by tanhh326** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/82007768/44d2f354-83e7-40e9-bdd7-8bef92198de3)
应该是这里的问题

**Comment by tanhh326** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/82007768/1a2a7a91-ff74-47b8-8cf4-16b20877afde)
应该是这里的`affixHeaderRef`的宽度计算的不正确吧，设置吸顶后有可能计算的比table的宽度小或者相等，或许可以设置成100%，不知道会不会有其它问题

**Comment by Summer-Shen** [comment]
> 推测是宽度计算，是否出现滚动条时出现了bug。 当窗口宽度缩小到一定程度，滚动条反而消失。 当窗口最大化，滚动条反而出现。

在特定的缩放比例下会出现多余的滚动条，我这边是 75%。可能确实是宽度计算。

**Comment by timi137137** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/d8febd42-f006-404c-b165-0aaaaca42ba8)
目前组件库版本1.8.1下这个滚动条会更加明显了，不会再出现阴间横杠的情况。本issue先关闭了如果有问题在开
