### ISSUE TITLE
有没有 同时支持 二、三级路由的 keep-alive 示例

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next-starter#420]
### 这个功能解决了什么问题

页面缓存

### 你建议的方案是什么

同时支持 二、三级路由的 keep-alive 有没有示例

**Comment by uyarn** [comment]
@timi137137 有没有空验证下这个问题

**Comment by timi137137** [comment]
> @timi137137 有没有空验证下这个问题

可以参考一下https://juejin.cn/post/7099355285172518920 但是按照业务逻辑上，通常不需要缓存（因为正常情况下每次打开一次页面就应该刷新一次数据）

**Comment by Jiachang-Cai** [comment]
> > @timi137137 有没有空验证下这个问题
> 
> 可以参考一下https://juejin.cn/post/7099355285172518920 但是按照业务逻辑上，通常不需要缓存（因为正常情况下每次打开一次页面就应该刷新一次数据）

通常不需要缓存 是不合理的 例如  业务场景 我 A 页面 操作页码到2 我新开其他页面(详情页、编辑页) 回来页面又重新刷回页码1了

**Comment by timi137137** [comment]
> > > @timi137137 有没有空验证下这个问题
> > 
> > 
> > 可以参考一下https://juejin.cn/post/7099355285172518920 但是按照业务逻辑上，通常不需要缓存（因为正常情况下每次打开一次页面就应该刷新一次数据）
> 
> 通常不需要缓存 是不合理的 例如 业务场景 我 A 页面 操作页码到2 我新开其他页面(详情页、编辑页) 切回页面A又重新刷回页码1了

对于这种情况通常都是另外一个标签页打开啊，有没有大厂例子可以看看，这个我可以研究一下

**Comment by Jiachang-Cai** [comment]
> 

就是新开页面切回原页面 如果重新刷新 就体验不好啊  keep-alive 支持二级路由是没有问题的 同时支持二、三级 暂搜不到很好的解决方案

**Comment by Jiachang-Cai** [comment]
> > > > @timi137137 有没有空验证下这个问题
> > > 
> > > 
> > > 可以参考一下https://juejin.cn/post/7099355285172518920 但是按照业务逻辑上，通常不需要缓存（因为正常情况下每次打开一次页面就应该刷新一次数据）
> > 
> > 
> > 通常不需要缓存 是不合理的 例如 业务场景 我 A 页面 操作页码到2 我新开其他页面(详情页、编辑页) 切回页面A又重新刷回页码1了
> 
> 对于这种情况通常都是另外一个标签页打开啊，有没有大厂例子可以看看，这个我可以研究一下


就是新开页面切回原页面 如果重新刷新 就体验不好啊 keep-alive 支持二级路由是没有问题的 同时支持二、三级 暂搜不到很好的解决方案

**Comment by timi137137** [comment]
> 

有代码场景可以让我测试吗...我这边对于你说的这个做法通常都是弹出model然后cancel的时候刷新数据。需要有个例子让我测试才能研究给你方案

**Comment by Jiachang-Cai** [comment]
> > 
> 
> 有代码场景可以让我测试吗...我这边对于你说的这个做法通常都是弹出model然后cancel的时候刷新数据。需要有个例子让我测试才能研究给你方案

![image](https://user-images.githubusercontent.com/8606851/219750613-364819d4-334d-4cb3-99bd-5065cd1403e2.png)
starter 就默认开了缓存的 
1. 使用 多标签Tab页
2. 列表页-基础列表页-选择页码2 随便点击一个数据的详情 切回 基础列表页 页码为还是2 
3. 现在是在这个基础上 再建个三级菜单 同时满足2的效果

**Comment by yixiaco** [comment]
> > > 
> > 
> > 
> > 有代码场景可以让我测试吗...我这边对于你说的这个做法通常都是弹出model然后cancel的时候刷新数据。需要有个例子让我测试才能研究给你方案
> 
> ![image](https://user-images.githubusercontent.com/8606851/219750613-364819d4-334d-4cb3-99bd-5065cd1403e2.png) starter 就默认开了缓存的
> 
> 1. 使用 多标签Tab页
> 2. 列表页-基础列表页-选择页码2 随便点击一个数据的详情 切回 基础列表页 页码为还是2
> 3. 现在是在这个基础上 再建个三级菜单(例如基础列表页 下面的子菜单) 同时满足2的效果

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/4ba8a0bd-7623-4bcd-9629-6019e0afdde7)
只要能够满足以上条件，就会被缓存到keep-alive中。
