### ISSUE TITLE
setting组件 页面配置样式错乱

### ISSUE THREAD

**Issue by sershine** [Tencent/tdesign-vue-next-starter#423]
### tdesign-vue-next-starter 版本

0.7.1

### 重现步骤

npm run dev后
进入页面，点击右上角齿轮，弹出页面配置组件
即可看到错乱样式

### 浏览器版本

Edge 110.0.1587.46

### 系统版本

Win10

### Node版本

16.7.0

**Comment by uyarn** [comment]
复现了  看起来应该是组件库升级的带来的一些样式变化这边没有跟进

**Comment by uyarn** [comment]
#425 暂时处理了问题 继续在 https://github.com/Tencent/tdesign-vue-next/issues/2422  跟进
