### ISSUE TITLE
【Vue Router warn]】No match found for location with path “xxx”

### ISSUE THREAD

**Issue by waney** [Tencent/tdesign-vue-next-starter#427]
### tdesign-vue-next-starter 版本

0.7.1

### 重现链接

https://tdesign.tencent.com/starter/vue-next/dashboard/base

### 重现步骤

刷新页面，
打开Console

### 补充说明

"vue": "^3.2.47",
"vue-router": "~4.1.6"

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/220134639-0809a8a4-53d1-4371-a5ca-0adca0583260.png)
这边无法复现

**Comment by waney** [comment]
@timi137137

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/220238407-8aa6b0be-dc11-44c2-9cc7-910f68f8b309.png)

**Comment by timi137137** [comment]
这个warn其实根本就不影响，而且启用了后端权限管理就必定有这个warn，也不是说出了warn页面就加载不了，所以没有解决办法，除非手动切换到前端权限管理

**Comment by waney** [comment]
> 

哈哈哈，不能认同，每次看到warn忍不了，
有两种可选方式：
1、/:catchAll(.*)  redirect: '/dashboard/base'
2、加临时路由
但总觉得不完美，还是想办法缓存或静态。

**Comment by timi137137** [comment]
> > 
> 
> 哈哈哈，不能认同，每次看到warn忍不了， 有两种可选方式： 1、/:catchAll(.*) redirect: '/dashboard/base' 2、加临时路由 但总觉得不完美，还是想办法缓存或静态。

我理解你想要清空所有warn的心态，但是后端权限控制的弊端就在这里，如果你从base跳过去的话是不会有这个问题的，但是如果你在除了静态路由外的地方刷新，就会出现这个问题。因为路由守卫还没运行，路由是空的。如果你全都缓存到pinia那你又要考虑如果刷新后当前用户权限被剥夺的话这个用户还有权限打开其他页面哦。所以这个问题是无解的。最好的办法就是切换回去前端权限控制
