### ISSUE TITLE
[tabs] 标签页可配置禁止拖拽

### ISSUE THREAD

**Issue by liweijie0812** [Tencent/tdesign-vue-next-starter#430]
### 这个功能解决了什么问题

<img width="776" alt="image" src="https://user-images.githubusercontent.com/10710889/220002706-6827a253-e305-49a4-b183-c68d45cb9c53.png">

### 你建议的方案是什么

希望加个参数可控制

**Comment by timi137137** [comment]
@liweijie0812 要不你顺便做了吧，因为你刚好有个PR开着( 我们现在手上活都有点多可能短期内没办法做

**Comment by liweijie0812** [comment]
> @liweijie0812 要不你顺便做了吧，因为你刚好有个PR开着( 我们现在手上活都有点多可能短期内没办法做

这个是tabs组件库的功能需求，可能是我截图举例不好

**Comment by liweijie0812** [comment]
![Untitled](https://user-images.githubusercontent.com/10710889/220240248-e624f99b-1615-43c7-a0d8-948c6d5a62a7.gif)

**Comment by liweijie0812** [comment]
> tabs 组件只有开启拖拽，子标签页想固定不允许拖拽没得控制 期望效果 ![Untitled](https://user-images.githubusercontent.com/10710889/220240248-e624f99b-1615-43c7-a0d8-948c6d5a62a7.gif) [ ![Untitled](https://user-images.githubusercontent.com/10710889/220240248-e624f99b-1615-43c7-a0d8-948c6d5a62a7.gif) ](https://user-images.githubusercontent.com/10710889/220240248-e624f99b-1615-43c7-a0d8-948c6d5a62a7.gif) [ ](https://user-images.githubusercontent.com/10710889/220240248-e624f99b-1615-43c7-a0d8-948c6d5a62a7.gif) 实际效果 ![Untitled](https://user-images.githubusercontent.com/10710889/220240914-ec4c0d19-82c1-44cd-b46d-aad67f8e1fde.gif) [ ![Untitled](https://user-images.githubusercontent.com/10710889/220240914-ec4c0d19-82c1-44cd-b46d-aad67f8e1fde.gif) ](https://user-images.githubusercontent.com/10710889/220240914-ec4c0d19-82c1-44cd-b46d-aad67f8e1fde.gif) [ ](https://user-images.githubusercontent.com/10710889/220240914-ec4c0d19-82c1-44cd-b46d-aad67f8e1fde.gif)

@PengYYYYY 这个应该算组件功能需求吧
