### ISSUE TITLE
动态路由页面刷新控制台会有警告

### ISSUE THREAD

**Issue by QAQCup** [Tencent/tdesign-vue-next-starter#431]
### 重现链接
https://tdesign.tencent.com/starter/vue-next/list/base

### 重现步骤
刷新页面https://tdesign.tencent.com/starter/vue-next/list/base

### 期望结果
动态路由页面刷新不出现警告

### 实际结果
![1676964265609](https://user-images.githubusercontent.com/47777659/220276030-c812aaf6-4183-4301-856a-0ff937c1699e.png)

| Environment | Info |
|---|---|
| 相关版本 | - |
| 框架版本 / 基础库版本 |  tdesign-vue-next-starter 0.7.1 |
| 系统、浏览器 | Chorme |
| Node版本 |  |

**Comment by QAQCup** [comment]
后端权限控制无法去掉这个警告是吗？

**Comment by timi137137** [comment]
是的------------------------------------------------------------------
***@***.***>
日　期：2023年02月22日 08:46:08
***@***.***>
***@***.***>; State ***@***.***>
主　题：Re: [Tencent/tdesign-vue-next-starter] 动态路由页面刷新控制台会有警告 (Issue #431)

后端权限控制无法去掉这个警告是吗？
