### ISSUE TITLE
能否集成全屏插件screenfull

### ISSUE THREAD

**Issue by lmxsoft** [Tencent/tdesign-vue-next-starter#433]
### 这个功能解决了什么问题
仪表盘、综合查询等功能，支持全屏效果会比较好。

### 你建议的方案是什么？
tabs标签增加右键菜单，【全屏展示】。

**Comment by lmxsoft** [comment]
您好！您的邮件已收到！我查阅后，尽快回复您！

**Comment by timi137137** [comment]
该模板是用来作为开始项目的，这类进阶使用场景推荐自行添加，或者可以fork仓库添加后由我们归类到docs中提供给开发者

**Comment by synctimes163** [comment]
import { useFullscreen } from '@vueuse/core'

const { isFullscreen, toggle } = useFullscreen()

安装 npm i @vueuse/core ，然后直接使用  

  <div class="setting-item" @click="toggle">
           <svg-icon
              :icon-class="isFullscreen ? 'fullscreen-exit' : 'fullscreen'"
            />
          </div>
