### ISSUE TITLE
能提供下三级菜单的demo吗

### ISSUE THREAD

**Issue by hexu2016** [Tencent/tdesign-vue-next-starter#440]
### 这个功能解决了什么问题

json里面,一级菜单是LAYOUT,二级菜单是LAYOUT还是BLANK呢?三级是正常页面的路径

### 你建议的方案是什么

如上

**Comment by timi137137** [comment]
二级菜单是由你自己定义的，只要有<router-view>标签就可以显示

**Comment by hexu2016** [comment]
> 二级菜单是由你自己定义的，只要有标签就可以显示

动态路由显示组件找不到,把它写成固定路由就正常..

**Comment by hexu2016** [comment]
> 二级菜单是由你自己定义的，只要有标签就可以显示

tips: 务必注意，三级菜单需要在二级菜单中的组件包含<router-view>标签才能正常显示，  
是要把二级菜单的component设置为BLANK吗

**Comment by hexu2016** [comment]
> 二级菜单是由你自己定义的，只要有标签就可以显示

二级和三级图标设置一样，会导致页面显示不出来。。
