### ISSUE TITLE
三级菜单好像有BUG

### ISSUE THREAD

**Issue by hexu2016** [Tencent/tdesign-vue-next-starter#441]
### tdesign-vue-next-starter 版本

0.7.2

### 重现步骤

二级三级菜单设置一样的图标,就会导致三级菜单内容加载失败

**Comment by uyarn** [comment]
没有复现这个问题 能不能提供下返回的菜单的数据

**Comment by hexu2016** [comment]
> 没有复现这个问题 能不能提供下返回的菜单的数据

之前描述不准确,目前是只要设置了2级菜单图标,就会导致3级菜单对应的内容打不开.. 还有二级菜单和三级菜单,是并列显示了,层次不够清晰,如果能使2级菜单文字左对齐,3级菜单文字右对齐呢?这样或许层次更清晰

**Comment by hexu2016** [comment]
![微信图片_20230309114133](https://user-images.githubusercontent.com/16769239/223910949-a44fc4cc-1b90-4cf7-9de7-818562012888.png)
[{"path":"/wygl","name":"wygl","id":"物业管理","component":"LAYOUT","meta":{"title":"物业管理","icon":"layers"},"children":[{"path":"industrySetting","name":"industrySetting","id":"产业信息管理","pid":"物业管理","component":"BLANK","meta":{"title":"产业信息管理"},"children":[{"path":"house","name":"HouseSetting","id":"房产信息","pid":"产业信息管理","component":"/wygl/industrySetting/house/index","meta":{"title":"房产信息"}}]},{"path":"systemSetting","name":"systemSetting","id":"系统设置","pid":"物业管理","component":"BLANK","meta":{"title":"系统设置","icon":"view-list"},"children":[{"path":"management","name":"ManagementSetting","id":"管理项目设置","pid":"系统设置","component":"/wygl/systemSetting/management/index","meta":{"title":"管理项目设置"}}]}]}]   把view-list去掉就正常了

**Comment by dufu1991** [comment]
我刚刚也遇到这个问题，一模一样。有办法修复吗？

**Comment by dufu1991** [comment]
三级菜单时，二级菜单不能添加icon，只要添加三级页面就出不来，报错与 [hexu2016] 提的一样。

**Comment by hexu2016** [comment]
我现在没管这个，你用新版本应该修复这个了吧



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月24日(周二) 上午9:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-vue-next-starter] 三级菜单好像有BUG (Issue #441)




 
我刚刚也遇到这个问题，一模一样。有办法修复吗？

**Comment by Liu-Peter** [comment]
我也遇到了，什么时候修复一下呀

**Comment by Hank-Zhou** [comment]
麻烦，要不就解决这个问题，要不就在文档上标注二级菜单别加icon。

**Comment by double-cool** [comment]
我现在也遇到了这个问题，如果在下面的二级菜单添加icon，则会出现上面一样的报错。三级页面无法访问
<img width="973" alt="企业微信截图_782326a6-e4bb-40e4-ab53-2d9e4cceacc1" src="https://github.com/user-attachments/assets/fe2971fc-48af-4139-b407-a7a6cc10fb5e">

  {
    path: '/dashboard',
    name: 'dashboard',
    component: Layout,
    meta: { title: '监控管理', icon: 'menu-fold' },
    children: [
      {
        path: 'video',
        meta: { title: '视频'},
        component: () => import('@/pages/dashboard/video/index.vue'),
        children: [
          {
            path: 'detail',
            name: 'VideoDetail',
            component: () => import('@/pages/dashboard/video/detail/index.vue'),
            meta: { title: '监控详情',icon: 'menu-fold' },
          },
          {
            path: 'map',
            name: 'VideoMap',
            component: () => import('@/pages/dashboard/video/map/index.vue'),
            meta: { title: '质量地图' },
          },
        ],
      },
    ],
  }
