### ISSUE TITLE
打包后路径出错

### ISSUE THREAD

**Issue by hexu2016** [Tencent/tdesign-vue-next-starter#443]
### tdesign-vue-next-starter 版本

0.7.2

### 重现步骤

上传到oss后,**********com/yt/index.html页面能访问到,但是资源路径错了,导致了404 
![image](https://user-images.githubusercontent.com/16769239/224272701-889f60a9-863a-4062-b0ca-07e0c32107ef.png)

**Comment by timi137137** [comment]
这个原因是因为你的VITE_BASE_URL设置问题，
![image](https://user-images.githubusercontent.com/36812439/224275655-266895be-3bea-44c2-8948-1e8f1cc7a05c.png)
不设置或者设置为null即可

**Comment by hexu2016** [comment]
> 这个原因是因为你的VITE_BASE_URL设置问题， ![image](https://user-images.githubusercontent.com/36812439/224275655-266895be-3bea-44c2-8948-1e8f1cc7a05c.png) 不设置或者设置为null即可

![image](https://user-images.githubusercontent.com/16769239/224285817-8cfe744b-dbaf-47ef-8fad-1136767e4d2b.png)
现在出现新问题了..就是按F5刷新的时候,又会出现404

**Comment by timi137137** [comment]
因为你要跳转的地方吧，%252Findex.html

**Comment by hexu2016** [comment]
> 因为你要跳转的地方吧，%252Findex.html

![image](https://user-images.githubusercontent.com/16769239/224306245-df2feb41-6291-4fec-bf2c-726a8da36aaf.png)
去年的版本是vite2.x，直接丢oss上面，路径里带有index.html就可以了，现在版本oss不知道怎么弄呢，nginx下面试了一下可以了
