### ISSUE TITLE
[Menu] 路由菜单项高亮问题，同一一级路由下，如两个二级路由的path以相同字符起始，菜单项高亮会重复

### ISSUE THREAD

**Issue by ngyyuusora** [Tencent/tdesign-vue-next-starter#444]
### tdesign-vue-next-starter 版本

0.7.2

### 重现步骤

![image](https://user-images.githubusercontent.com/28800738/224272613-c23500c6-2207-454a-ab5b-e4ea3486d902.png)
使两个二级路由的path以相同字符起始，在此，路由1和路由2的path均以'advanced'起始。
![image](https://user-images.githubusercontent.com/28800738/224273014-2e7ee08f-2e39-4505-8211-a5d1ab11b691.png)
菜单激活为路由1时无问题，切换到路由2就会出现路由1和路由2的菜单同时高亮。
![image](https://user-images.githubusercontent.com/28800738/224273173-f7a9f157-c641-4c35-bec6-b3d406fef7c9.png)

### 期望结果

二级菜单项高亮不重复。

### 实际结果

![image](https://user-images.githubusercontent.com/28800738/224273173-f7a9f157-c641-4c35-bec6-b3d406fef7c9.png)

### 浏览器版本

Chrome(110.0.5481.178)

### 补充说明

简单测试，如果是使用kebab-case，第一段重复也会导致这个问题（毕竟横杠也算是字符），大小写好像也会出现。两个二级菜单无论是否相邻也会出现。
![image](https://user-images.githubusercontent.com/28800738/224273650-ebcc2b6d-d691-404e-937c-74fd304a2306.png)
![image](https://user-images.githubusercontent.com/28800738/224273937-e77315cc-5972-4ea3-99fa-73a4317edfac.png)
没有细看，可能是这里导致重复高亮（菜单项的value和当前路由匹配上了）。不影响实际路由切换功能，只是高亮显示问题。但在路由1激活时，他的value是正确的，激活path相同起始的路由2，结果路由1的value就变了

**Comment by ngyyuusora** [comment]
经测应该是只有当路由1的path值完全被路由2包含时会出现这种问题。

**Comment by timi137137** [comment]
估计是路由相关匹配有这堆问题（扶额）

**Comment by ngyyuusora** [comment]
问题场景，path值，路由1为user，路由2为user-log

**Comment by dianjie** [comment]
@timi137137 https://github.com/Tencent/tdesign-vue-next-starter/blob/0.7.2/src/layouts/components/MenuContent.vue#L88
这里的判断影响的
