### ISSUE TITLE
能否增加全屏按钮功能？

### ISSUE THREAD

**Issue by jaychou2012** [Tencent/tdesign-vue-next-starter#446]
### 这个功能解决了什么问题

顶部右上角能否增加全屏按钮功能？点击后，可以将后台页面全屏展示。

### 你建议的方案是什么

顶部右上角能否增加全屏按钮功能

**Comment by jaychou2012** [comment]
E-MAIL 已收到。

**Comment by timi137137** [comment]
该功能不太普遍，因此不能集成到模板中，您可以自己添加
