### ISSUE TITLE
能否增加实际接入开放平台的微信扫码登陆示例

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next-starter#451]
### 这个功能解决了什么问题

微信扫码登陆

### 你建议的方案是什么

微信扫码登陆

**Comment by waney** [comment]
这个应该自己实现吧，登录界面生成带场景值的二维码，扫码后在服务器端得到携带参数的事件，前端界面轮询状态判断是否登录。

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/227866056-9b600924-6f74-4ab5-a74a-aecf25307ec6.png)
我们已经模拟并留出接口了，其余的只能您自己实现
