### ISSUE TITLE
[导航菜单] 菜单后面的图标隐藏了

### ISSUE THREAD

**Issue by superextend** [Tencent/tdesign-vue-next-starter#455]
### tdesign-vue-next-starter 版本

能

### 重现链接

https://tdesign.tencent.com/starter/vue-next/dashboard/detail

### 重现步骤

![QQ图片20230328102206](https://user-images.githubusercontent.com/58968749/228111281-0e55e239-3da8-4ed2-9906-0f89142f8c6c.png)
菜单右边图标看不到了
![QQ图片20230328102742](https://user-images.githubusercontent.com/58968749/228111469-3a247b3d-a76e-43ae-9869-9913dc4458fa.png)

### 系统版本

windows10

**Comment by timi137137** [comment]
样式炸了这个确实有问题
@uyarn 主题包那边顺手修复了？

**Comment by uyarn** [comment]
和 https://github.com/Tencent/tdesign-vue-next/issues/2779 本质是一个问题 对封装组件的子菜单处理逻辑没有考虑到 在这个issue统一跟进下
