### ISSUE TITLE
[Router] 希望可以直接在路由列表中配置路由meta是否keep-alive保活

### ISSUE THREAD

**Issue by ngyyuusora** [Tencent/tdesign-vue-next-starter#469]
### 这个功能解决了什么问题

目前对一个页面禁用多标签tab页（依赖keep-alive）黑名单的配置，需要在src/store/modules/tab-router.ts中的ignoreCacheRoutes平铺单独配置路由的name。同时，禁用多标签tab页后，虽然没有多标签了，但依然会对打开的页面进行keep-alive保活（这个特性应该不需要修改，只是如果页面不需要保活，不能理解为通过关闭多标签即可关闭）。

### 你建议的方案是什么

希望可以直接在路由列表中路由的meta属性中添加multi-tabs或者keep-alive属性来配置黑名单，使这个路由不被保活，这样用起来方便一些。在ignoreCacheRoutes中平铺配置如果页面多了可能不好管理，调整路由需要多调整一个tab-router.ts文件（如需不保活）。

**Comment by uyarn** [comment]
确实应该加到配置里比较方便

**Comment by uyarn** [comment]
refer to https://github.com/Tencent/tdesign-vue-next-starter/pull/470
