### ISSUE TITLE
[导航布局] 主导航不能固定。

### ISSUE THREAD

**Issue by yanshicheng** [Tencent/tdesign-vue-next-starter#473]
### tdesign-vue-next-starter 版本

1.3.0

### 重现步骤

设置布局
<img width="496" alt="image" src="https://user-images.githubusercontent.com/37960656/232283861-e67f140f-6b82-492f-abaf-f5d77d54708d.png">

异常，点击主导航，上面就变成三个点不能固定住，vue 版本没问题，vue next 有这个问题
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37960656/232283829-0d40cbe7-6d51-4478-b32b-ce0feac93a69.png">

只有点击子导航才会正常
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/37960656/232283968-9d254dd7-5f16-4f13-ac9e-e283e992076d.png">

### 期望结果

主导航根据设置，保持不变

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/232315609-e6f09e12-0264-4121-84d1-1d5bae94120e.png)
能提供复现方法吗

**Comment by liweijie0812** [comment]
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/10710889/232362137-baab956a-d1d4-46fa-9803-1b77f390d8aa.png">
笔记本屏幕小就会

**Comment by yanshicheng** [comment]
不是屏幕小就会吧，再点击 统计报表就好了

**Comment by yanshicheng** [comment]
# 打开演示站点，修改设置
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/37960656/232374122-0dda1bee-aaf3-49ff-934c-5f369822655c.png">
# 刚开始修改是没问题的
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/37960656/232374165-b9e8c1c0-6da4-4026-9ca5-987469acb73c.png">
# 随便点击详情页出现问题
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/37960656/232374247-9104c810-dca3-4a8d-9fea-8868c66dfb22.png">

# 再点击二级菜单恢复
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/37960656/232374331-489bac00-8d59-4925-bec1-22dac269722e.png">


# 总结
就很奇怪就很怪，vue那个版本就没问题，vue next 有问题。  
这样体验感受有点差

**Comment by yanshicheng** [comment]
这是bug 吗，还是故意设计的？没有看懂

**Comment by yanshicheng** [comment]
是屏幕小的问题导致的吗？还是什么问题

**Comment by timi137137** [comment]
第一是菜单列表的样式问题
Tencent/tdesign-vue-next#1881
![image](https://user-images.githubusercontent.com/36812439/232768149-d2022bac-593b-47d5-88d6-249808349c73.png)
第二是因为菜单过长默认从第一项缩小了，理想情况为最后一项缩小
@uyarn 组件库老毛病了，我N久之前提过了，看起来没修好
