### ISSUE TITLE
tdesign-icons-vue-next中的manifest图标列表引入报错

### ISSUE THREAD

**Issue by doukaiwei** [Tencent/tdesign-vue-next-starter#474]
### tdesign-vue-next-starter 版本

"tdesign-vue-next": "^1.2.2",

### 重现步骤

在页面中引入tdesign-icons-vue-next中的manifest后，在项目中进入该页面会控制台报错，导致界面空白，并且取消引用后，控制台报错会一直存在

### 期望结果

可以正常使用，控制台不产生报错

### 框架版本

"vue": "^3.2.47",

### 浏览器版本

chorm 111.0.5563.149

### 系统版本

window10

### Node版本

v16.19.1

**Comment by uyarn** [comment]
vite 默认支持module 可以改成 import { manifest } from 'tdesign-icons-vue-next' 使用哈 文档我们也更新了
https://github.com/Tencent/tdesign-vue-next/pull/2739
