### ISSUE TITLE
启动时DevTools提示Uncaught TypeError: isFunction is not a function

### ISSUE THREAD

**Issue by liufengvling** [Tencent/tdesign-vue-next-starter#477]
### tdesign-vue-next-starter 版本

0.7.4

### 重现步骤

开发时不定时出现【Uncaught TypeError: isFunction is not a function】如下图，删除node_modules,回退所有改动代码重新安装也无用

![111111111111111](https://user-images.githubusercontent.com/5516194/234732081-09178065-de8f-49b4-85e5-4c16c605eec9.png)

**Comment by timi137137** [comment]
这个情况是因为loadsh包没有正确被打包，本地没发现该问题，有稳定复现方法吗

**Comment by liufengvling** [comment]
@timi137137   已解决，使用低版本icon引入写法导致的
`import { manifest } from 'tdesign-icons-vue-next/lib/manifest';`
改为下面写法正常了
`import { manifest } from 'tdesign-icons-vue-next';`
