### ISSUE TITLE
[国际化] 有计划增加国际化功能吗？

### ISSUE THREAD

**Issue by lan-yonghui** [Tencent/tdesign-vue-next-starter#478]
### 这个功能解决了什么问题

语言国际化

### 你建议的方案是什么

语言国际化插件组成或者自研组件？

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-next-starter/pull/457 下周上线 等个语言切换的图标

**Comment by lan-yonghui** [comment]
nice

**Comment by liweijie0812** [comment]
https://github.com/Tencent/tdesign-vue-next-starter/releases/tag/0.9.0
