### ISSUE TITLE
组件缓存失效

### ISSUE THREAD

**Issue by R-1018** [Tencent/tdesign-vue-next-starter#489]
### tdesign-vue-next-starter 版本

最新

### 重现步骤

根据文档描述 路由有name参数 需要和组件名一致
![image](https://user-images.githubusercontent.com/110664796/237041414-171f323f-98f5-4b38-9c5e-281b39fb8801.png)
我没有改变router里面任何参数 根据文档来复现
![image](https://user-images.githubusercontent.com/110664796/237041567-673acc72-9fab-4df0-9f22-6a2d4271dda6.png)
在我输入内容之后切换掉页面 输入框参数会消失

页面只有一个简单和input组件 未v-model 会不会是这个问题?

**Comment by uyarn** [comment]
<img width="854" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/26377630/48b25a18-28df-4f0a-b8bf-ed380dc79174">
这里有说明
