### ISSUE TITLE
[dashboard] echarts在edge浏览器中报错

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next-starter#498]
### tdesign-vue-next-starter 版本

0.7.4

### 1.这种写法打包到nginx中运行后会在Edge浏览器中报错。注入html元素ref同名变量失败。因为echarts要求不能使用ref方式注入HTMLElement元素，因此应该在html元素中删除ref
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/33664c5c-6be3-4934-a53d-4517769dd7be)
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/c9ff3944-ff50-44d5-b163-50ef8e2305c0)

### 2.没有指定文件后缀，引入多个同名文件导致编译器标红
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/10ba698f-c23f-488f-ac97-e822938d076e)

### 框架版本

Vue(3.2.47) Vite(4.2.1)

### 浏览器版本

Microsoft Edge版本 113.0.1774.35 (正式版本) (64 位)

### 系统版本

Windows10

### Node版本

16.15.0

**Comment by liweijie0812** [comment]
在vite4打包后是有问题，vite3打包正常

**Comment by yixiaco** [comment]
> 在vite4打包后是有问题，vite3打包正常

应该是，盘查了很久才定位到这个问题

**Comment by liweijie0812** [comment]
> > 在vite4打包后是有问题，vite3打包正常
> 
> 应该是，盘查了很久才定位到这个问题

vite4 发布后我就尝试过升级，开发模式正常，打包后才会报错
