### ISSUE TITLE
[Router] 支持不带children的跟路由配置

### ISSUE THREAD

**Issue by SpringHgui** [Tencent/tdesign-vue-next-starter#499]
### 这个功能解决了什么问题

1. 当前所有的路由都是带有`children`的，但是有些场景展示的菜单不全是这样带有折叠的子菜单形式
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/22363718/e3018930-461d-482c-8dd0-48be94c6d8f3)

2. 比如上面的`概览仪表盘`我想把他放在最外层的菜单上，目前的设计是否？如果支持，怎么配置将下图的中菜单提到最外层
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/22363718/2bd2dda2-ba45-4fb1-9533-c308667b7f0d)

### 你建议的方案是什么

无

**Comment by uyarn** [comment]
你可能需要这个 
<img width="976" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/26377630/eeeb4f05-7f47-4064-b852-60d2195af95c">
https://tdesign.tencent.com/starter/docs/vue-next/router-menu
