### ISSUE TITLE
[编辑器代码风格] 默认IDE换行方案

### ISSUE THREAD

**Issue by SpringHgui** [Tencent/tdesign-vue-next-starter#503]
### 这个功能解决了什么问题

请问在在不同的开发者环境下，默认创建的文件换行，以及缩进是不符合该项目规范，虽然最终可以通过`lint-staged`钩子进行自动格式化修正，是否在代码未提交前就通过IDE的特性进行优化呢

我的vs都是默认环境，新建文件，换行和缩进都是不符合规范的。

@uyarn 请大佬解答下是否有这个必要
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/22363718/28aaac27-1c0d-439d-bff9-cd6c389fa153)

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/22363718/1a610ae0-1bb7-47b5-acfa-f58b49fec58c)

### 你建议的方案是什么

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/22363718/85c72fa1-e3aa-4f09-910c-2c4ef4fa3d4d)

https://github.com/Tencent/tdesign-vue-next-starter/pull/492

**Comment by uyarn** [comment]
@SpringHgui 有的 我在vue的仓库看到了这个改动 有回复你 这边也可以提交这个改动

**Comment by SpringHgui** [comment]
好的，这个PR也是被否了 #492

**Comment by yunxifd** [comment]
我不认为vscode settings.json 有效。代码换行符其实`.editorconfig`，`.prettierrc.js`文件已经配置了，可以保证在开发过程中换行符一致。
唯一不能覆盖的地方时，拉取代码的时候，在Windows平台上，git默认的core.autocrlf是true。导致拉下来的代码文件(lf)自动更改换行符为crlf
## 方法一
禁用自动转换
```
git config --global core.autocrlf false
```
缺点，就是每个开发者都要在电脑上修改一下设置，而且

## 方法二 （推荐）
使用`.gitattributes` 文件，配置不同类型文件行结束符如何处理，项目范围.gitattributes配置会覆盖git全局core.autocrlf的配置

例如
```
*.vue text eol=lf
```

## 参考
https://juejin.cn/post/6942320745494085669

**Comment by uyarn** [comment]
@yunxifd 学习了 @SpringHgui 看了些参考 感觉下面这个方式调整也许更合适些

**Comment by SpringHgui** [comment]
可以试试效果，能完美解决最好了

**Comment by SpringHgui** [comment]
经过测试初次拉下来的代码格式没问题，新创建的文件依然存在格式问题，是否这两个解决方案是互补的？
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/22363718/f495b62f-e03a-4b74-a062-e71fa23b16de)

**Comment by SpringHgui** [comment]
# 505 @yunxifd 有什么补充吗

**Comment by yunxifd** [comment]
@SpringHgui 新建的文件的确是 crlf，只有在编辑器里保存一次后prettier才会将其换成 lf。可以互补一下

**Comment by SpringHgui** [comment]
> @SpringHgui 新建的文件的确是 crlf，只有在编辑器里保存一次后prettier才会将其换成 lf。可以互补一下

感谢，学到了
