### ISSUE TITLE
是否计划pinia替代vuex

### ISSUE THREAD

**Issue by qingmang** [Tencent/tdesign-vue-next-starter#51]
如今大多vue3组件都开始使用pinia替代vuex 咱们这个还用的vuex 是否考虑更换

**Comment by chaishi** [comment]
感谢建议，大家都回家过年了，来年可以一起看看

**Comment by pengYYYYY** [comment]
> 如今大多vue3组件都开始使用pinia替代vuex 咱们这个还用的vuex 是否考虑更换

有计划的喔，也会使用setup script

**Comment by wincheer** [comment]
> 

在眼巴巴等着 setup script和pinia 。一旦换过来，我就开始尝试使用到实际项目中

**Comment by pengYYYYY** [comment]
setup script 和 pinia 已经替换了
