### ISSUE TITLE
[布局导航] 布局导航混合模式bug

### ISSUE THREAD

**Issue by y17800219757** [Tencent/tdesign-vue-next-starter#520]
### tdesign-vue-next-starter 版本

0.7.5

### 重现步骤

布局导航混合模式有bug，应该在最后进行缩率吧，怎么跑到前面了
<img width="1360" alt="e2a4a60fa279292f422f55e5bffe3fb" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/63292638/967461fd-eb73-4bc7-91cc-7c419caa3578">

### 期望结果

修复布局导航混合模式bug

**Comment by timi137137** [comment]
这个问题我也提n年了（摊手）------------------------------------------------------------------
***@***.***>
日　期：2023年05月24日 11:19:31
***@***.***>
***@***.***>
主　题：[Tencent/tdesign-vue-next-starter] [布局导航] 布局导航混合模式bug (Issue #520)

tdesign-vue-next-starter 版本
0.7.5 重现链接
No response 重现步骤
布局导航混合模式有bug，应该在最后进行缩率吧，怎么跑到前面了
 期望结果
修复布局导航混合模式bug 实际结果
No response 框架版本
No response 浏览器版本
No response 系统版本
No response Node版本
No response 补充说明
No response

**Comment by timi137137** [comment]
这个问题可以先在 layouts/MenuContent.vue中将最外层的<div>删除即可恢复，但是会出现小屏幕将右边挤掉的现象，这边正在解决，下周发版能搞定这个问题
