### ISSUE TITLE
[项目init] 项目初始化获取列表失败

### ISSUE THREAD

**Issue by yanshicheng** [Tencent/tdesign-vue-next-starter#521]
### tdesign-vue-next-starter 版本

0.7.5

### 重现步骤

请问这是什么问题
<img width="1427" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/37960656/1336dd0f-11e1-422d-8fc7-a9a177c4c977">
<img width="1126" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/37960656/94cf90b6-8bad-4d9b-9ba2-2aeeb574e90f">

**Comment by timi137137** [comment]
你只给个红框谁能帮你呢....

**Comment by yanshicheng** [comment]
<img width="1529" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/37960656/57f745e4-f39d-4834-80e7-0005af5a56d4">
请求登陆一直在请求get-menu-list

**Comment by yanshicheng** [comment]
本地clone 的代码，

**Comment by timi137137** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/d9c0d187-f0c2-4d4c-be62-909bf73ffc39)
本地没复现

**Comment by yanshicheng** [comment]
我在找找问题，谢谢。请问日志rundev 默认不打印吗

**Comment by timi137137** [comment]
> 我在找找问题，谢谢。请问日志rundev 默认不打印吗

模板没有输出任何日志，毕竟是开箱即用，如果附带日志导致用户正式环境出现问题就不好了

**Comment by yanshicheng** [comment]
好的谢谢，菜单分栏问题缩略，大佬可以处理下，发个版出来么

**Comment by timi137137** [comment]
> 好的谢谢，菜单分栏问题缩略，大佬可以处理下，发个版出来么

（捂脸）
#340
#520 
#473 
我也很无奈，我去催催

**Comment by yanshicheng** [comment]
谢谢，

**Comment by yanshicheng** [comment]
大佬您可以再试一下，我用的vue2初始化，项目正常。
vue3初始化，登陆会显示成功，但是会卡在获取菜单列表那里

**Comment by timi137137** [comment]
我们这边经过几个人排查发现都没问题，应该是你那边本地网络有异常，可以看看排查一下

**Comment by yanshicheng** [comment]
好的

**Comment by PDieE** [comment]
是不是 开了什么 vpn 把项目的接口代理给冲掉了
或者拉下来之后是否有改过什么？
因为这个模板他登录那边是不请求接口，就装了个样子，所以登录一定不会出现网络问题，但是进入页面后的请求基本上都是走的mock

**Comment by yanshicheng** [comment]
网络都断开了，梯子也退了，还是有问题
<img width="1548" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/37960656/5c8df16b-f627-4133-9097-eb4774a7f8a2">

**Comment by yanshicheng** [comment]
找到了，vue3初始化是不是有点问题，大佬可以 fix
<img width="1044" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/37960656/71dc60c8-bd3f-4449-a788-952cb64046a3">
