### ISSUE TITLE
这里在页面重载时取不到token，

### ISSUE THREAD

**Issue by waney** [Tencent/tdesign-vue-next-starter#524]
https://github.com/Tencent/tdesign-vue-next-starter/blob/89ccf19f586f681bccdde62219f6cfa13999630e/src/utils/request/index.ts#LL118C4-L118C41
```
    const userStore = getUserStore();
    const token = userStore[TOKEN_NAME];
```
Axios请求时 Store的数据还没有。
可以用 hot-reload 观察。

**Comment by timi137137** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/6c9041d8-5c0e-4a9d-b6ff-89469499b193)
请求之前肯定没token啊....判断token是否存在在下面

**Comment by waney** [comment]
你可能没理解，我的意思是指，本来已经有token的，这时候由于页面hot-reload，此时store为空，导致请求时没有token而造成401未授权。

**Comment by waney** [comment]
store赋值在Axios请求之后。

**Comment by timi137137** [comment]
我确认一下，你说的hot reload是不是Vite HMR

**Comment by waney** [comment]
那意味着token存ls里更合适。

**Comment by timi137137** [comment]
你跟我说没用，有人非要存这里

**Comment by waney** [comment]
哈哈哈，理解，相信他会懂的

**Comment by timi137137** [comment]
那这个issue我先关闭了，这个事情你开个pr问问他算了（埋了自己）

**Comment by waney** [comment]
> 那这个issue我先关闭了，这个事情你开个pr问问他算了（埋了自己）

哈哈，不用问了，显而易见的事，可以按自己的目的修改。

**Comment by waney** [comment]
[https://github.com/prazdevs/pinia-plugin-persistedstate/issues/79](https://github.com/prazdevs/pinia-plugin-persistedstate/issues/79)

#[core] Object data is empty after HMR (Hot Module Replacement) reload #79
