### ISSUE TITLE
[路由权限permission.ts文件] 换一个角色登录后还会保留上一角色的路由信息

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next-starter#541]
### tdesign-vue-next-starter 版本

0.25.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/19531939/82182ca3-f65c-4c2c-98a9-447e411ca392)

在@/store/permission.ts文件中过滤路由函数这里，当角色登录后，会缓存上一个角色的部分路由，然后必须要刷新一次，路由才能恢复正常。

### 期望结果

希望每次不同角色登录后，不要路由权限过滤这里不要缓存上一个角色的路由信息。这样不同角色登录后不需要刷新，就可以正确拿到各自权限的路由信息

**Comment by ngyyuusora** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/28800738/8a764e54-ace3-4ace-bbdf-250811146bab)
这样修复就可以实现需求， 我提个pr

**Comment by huyiwill** [comment]
我用的是     "tdesign-vue-next": "^0.25.0",   版本；改的是this.router 但是还是不行。以下截图是未修改过的原版










在 2023-06-20 12:59:39，"ngyyuusora" ***@***.***> 写道：


这样修复就可以实现需求， 我提个pr

**Comment by timi137137** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/e8825037-b2d6-44a5-abc0-5fbbcfc9a30c)
虽然但是我可能没看见图片，but 欢迎PR

**Comment by ngyyuusora** [comment]
> 我用的是 "tdesign-vue-next": "^0.25.0", 版本；改的是this.router 但是还是不行。以下截图是未修改过的原版 在 2023-06-20 12:59:39，"ngyyuusora" ***@***.***> 写道： 这样修复就可以实现需求， 我提个pr — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

抱歉哦没有留意你的版本，因为相关逻辑大改过，可以考虑通过upstream方式来拉取最新版本到starter进行完善。
如项目修改过多不方便升级，可以参考最新版本，搜索asyncRoutes看相关逻辑，都手动合并到你的项目试试
