### ISSUE TITLE
[Icons] 网站Icon图标请求CDN而不是打包的svg文件

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next-starter#542]
### tdesign-vue-next-starter 版本

0.7.6

### 图标走的是tdesign.gtimg.com这个域名
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/bdde2997-9cb2-403c-809e-f2a46c97d80a)
### 请求域禁用时，图标就无法加载了
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/668da607-d344-49ac-a26d-6f8d87ee05a8)
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/30982989/fbb27657-0544-4c4a-8869-58c64eb746ea)

如果是在内网环境无法请求外网的情况下，是否就会造成icon显示异常

**Comment by timi137137** [comment]
详情请看https://tdesign.tencent.com/vue-next/components/icon#faq

**Comment by yixiaco** [comment]
> 详情请看https://tdesign.tencent.com/vue-next/components/icon#faq

明白了，也就是说，t-icon就会发起网络请求。如果是动态名称的图标还要自己封装一个组件把图标全部import进来遍历显示吧

**Comment by timi137137** [comment]
yes

**Comment by yixiaco** [comment]
> yes

OK
