### ISSUE TITLE
主题切换能指定默认的配置吗？

### ISSUE THREAD

**Issue by imaxun** [Tencent/tdesign-vue-next-starter#543]
### 这个功能解决了什么问题

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/29112991/974fd6c9-e55b-4262-99f5-9f06990e18c2)
比如我想默认使用tcloud的这个主题

### 你建议的方案是什么

比如我想默认使用tcloud的这个主题

**Comment by uyarn** [comment]
可以点击下载按钮 把下载下来的文件放到项目里import进来 默认就是tcloud了

**Comment by imaxun** [comment]
不需要把默认的主题给剔掉吗，我import 但是样式还是不是tcloud的那样
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/29112991/7f62a540-8a5b-4fde-afb8-64aa81ac9bc3)
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/29112991/d8c8831f-383d-41d0-9588-114baa68a6ec)

**Comment by timi137137** [comment]
那肯定是要移除默认的样式文件的，下载下来直接替换内容也是可以的。
