### ISSUE TITLE
希望有权限管理，用户、角色，这样更方便上手了

### ISSUE THREAD

**Issue by wincheer** [Tencent/tdesign-vue-next-starter#55]
首先感谢TDesign团队。
这个starter很漂亮，速度也很快。如果加上用户/角色权限管理，就更棒了。

**Comment by qingmang** [comment]
动态路由 权限相关示例

**Comment by pengYYYYY** [comment]
动态路由相关的逻辑现在已经内置了，只是没有做相关的展示，后面会进一步增强功能的。有什么好的想法也欢迎一起共建，
