### ISSUE TITLE
[ECharts] 升级ECharts版本相关问题

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next-starter#555]
### tdesign-vue-next-starter 版本

0.7.7

### 重现步骤

目前EC版本为5.1.2
最新版本为5.4.2
但已知升级到5.4会出现打包后图例样式错乱问题

**Comment by uyarn** [comment]
你这个应该去echarts 开个issue track下吧？

**Comment by timi137137** [comment]
> 你这个应该去echarts 开个issue track下吧？

主要是我现在不太清楚是我们的问题还是他们的问题（思考）

**Comment by timi137137** [comment]
(? 挺见鬼的，5.4.3似乎修好了
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/be281b8a-5b1b-46e9-9d77-ff23f881c775)
