### ISSUE TITLE
[t-link] 在设置 theme 属性时 hover 效果颜色错误

### ISSUE THREAD

**Issue by brankcar** [Tencent/tdesign-vue-next-starter#564]
### tdesign-vue-next 版本

1.3.10

### 重现步骤

`<t-link theme="danger">删除</t-link>`

### 期望结果

hover 效果应该为 danger 颜色

### 实际结果

hover 目前为 primary 颜色

**Comment by liweijie0812** [comment]
在改，pr晚点推

**Comment by liweijie0812** [comment]
> 麻烦顺便也看看 layouts/setting.vue 文件内的样式影响

这个问题你另外开一个issue描述吧

**Comment by brankcar** [comment]
> > 麻烦顺便也看看 layouts/setting.vue 文件内的样式影响
> 
> 这个问题你另外开一个issue描述吧

ok
