### ISSUE TITLE
[tsconfig.json] 在tsconfig中vite/client未找到

### ISSUE THREAD

**Issue by shen774411223d** [Tencent/tdesign-vue-next-starter#568]
### tdesign-vue-next-starter 版本

0.8.0

### 重现步骤

从github上 git clone的项目。
在根目录 tsconfig.json文件中的types属性引用了 vite/client 包，但是这个包 `@types/vite`在npmjs中找不到，我应该如何下载这个包呢？
```
// tsconfig.json
{
  "compilerOptions": {
      "types": ["vite/client"],
}
}
```
报错信息为：
找不到“vite/client”的类型定义文件。
  程序包含该文件是因为:
    在 compilerOptions 中指定的类型库 "vite/client" 的入口点

**Comment by timi137137** [comment]
这个是vite自带的，安装了vite就一定会有
如果保存那就是本地的类型检测服务有问题，重启就好
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/de88f706-7dff-44dc-93ca-62301b1a73b4)
