### ISSUE TITLE
可否写个文档/视频，讲一下代码逻辑？

### ISSUE THREAD

**Issue by wincheer** [Tencent/tdesign-vue-next-starter#57]
可否写个文档（如果录一段视频或者直播就更好了），讲一下代码逻辑？
不用太详细，只需要把代码串起来就好，顺便解释一下以此为基础的开发流程。
作为一个半吊子的vue初学者（本人是开发后端的），完全自己啃代码太吃力

**Comment by pengYYYYY** [comment]
现在有starter的文档，然后这一块有up主正在计划出相关的视频，敬请期待。

**Comment by qingmang** [comment]
啥时候更新啊 紧度有点慢啊

**Comment by uyarn** [comment]
我们在文档中增加了社区的视频链接文档 https://tdesign.tencent.com/starter/docs/vue/community-link 后面会继续更新这块的内容
