### ISSUE TITLE
能否增加打包时的加密混淆，在正式环境打包时生效或改为可配置项，是否开启打包的加密混淆

### ISSUE THREAD

**Issue by yuzunyue** [Tencent/tdesign-vue-next-starter#571]
### 这个功能解决了什么问题

打包时的加密混淆

### 你建议的方案是什么

打包时的加密混淆

**Comment by timi137137** [comment]
不考虑添加此功能，本模板为开箱即用模板，有需要可以自行研究
https://huaweicloud.csdn.net/639fea4adacf622b8df8fdfa.html
