### ISSUE TITLE
tdesign-vue-next-starter 更新的好慢呀 国际化跟主题配色在main分支都有

### ISSUE THREAD

**Issue by imaxun** [Tencent/tdesign-vue-next-starter#574]
### 这个功能解决了什么问题

tdesign-vue-next-starter 更新的好慢呀 国际化跟主题配色在main分支都有

### 你建议的方案是什么

希望更新的频率快一些

**Comment by uyarn** [comment]
国际化的功能我们尽快安排上 最近其他事情比较多 这边没腾出精力来弄

**Comment by timi137137** [comment]
link #457

**Comment by imaxun** [comment]
感觉整体布局也不是很完善，阿里，字节的都比较简约。希望能tx的也能越做越好吧

**Comment by timi137137** [comment]
简约是指...？

**Comment by imaxun** [comment]
> 是指...？

总感觉tdesign-vue-next-starte的设计有点偏土，你看下其他的ui你就知道我想描述的了

**Comment by imaxun** [comment]
<img width="1116" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/29112991/75d6100b-e529-41d0-b0d6-20c2b50669cf">
<img width="1437" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/29112991/267ed548-b4d8-47f9-ac1f-e3adabbcf365">
这是我看过的其他的

**Comment by timi137137** [comment]
这个...实话说我只能帮你提交给设计组那边问问，但是感谢你们支持TDesign

**Comment by hmingv** [comment]
@timi137137 请问对国际化的支持有新的计划了吗？大约多久可以上线呢
