### ISSUE TITLE
分割菜单模式下建议也显示图标以及收缩功能

### ISSUE THREAD

**Issue by imaxun** [Tencent/tdesign-vue-next-starter#585]
### 这个功能解决了什么问题

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/29112991/71314f82-ea54-46a5-be11-a0b77b70e005)

### 你建议的方案是什么

分割菜单模式下建议也显示图标以及收缩功能

**Comment by timi137137** [comment]
![image](https://github.com/user-attachments/assets/2cd99359-db21-4b80-bc7a-3e045e5b2bd8)
已经完成该功能，可以在二级菜单添加icon实现
