### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by Nice-PLQ** [Tencent/tdesign-vue-next-starter#597]
### tdesign-vue-next-starter 版本

0.8

### 重现链接

https://tdesign.tencent.com/starter/vue-next/list/card

### 重现步骤

切换菜单的时候，内容区域，会同时出现下一个菜单的内容，同时当前菜单的内容会按opacity逐渐退出。此时就会导致两个菜单对应的内容同时出来，然后等当前菜单内容退出后，下一个菜单的内容就会顶上去，导致抖动的现象。

官网就可以复现，多切换下菜单试试

### 实际结果

<img width="2596" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/10710341/ca4fe079-f83f-4adb-b0dd-34aa19691597">

**Comment by timi137137** [comment]
link #320
同一个类型的问题，我没有复现出你这个情况，但估计是因为自动scroll回顶触发的问题

**Comment by timi137137** [comment]
与 #320 重复，关联并关闭
