### ISSUE TITLE
暗黑主题登录输入框背景不应该透明

### ISSUE THREAD

**Issue by dufu1991** [Tencent/tdesign-vue-next-starter#602]
### tdesign-vue-next-starter 版本

0.8.0

### 重现链接

https://tdesign.tencent.com/starter/vue-next/login

### 重现步骤

打开 https://tdesign.tencent.com/starter/vue-next/login 这个地址，点击右上角主题改为暗黑，适当缩小页面左右宽度，使登录框底部不要是纯黑画面，就会发现登录的输入框背景是透明的，影响了文字效果。
如果设计如此，那么明亮主题时又有白色背景，所以推测是开发时暗黑主题没考虑好。
对比一下。
<img width="739" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/24769077/ea8124f7-e177-4204-acf4-e982fa003586">
<img width="702" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/24769077/8e35ec90-5d14-4332-ae95-c287701c3b65">

### 期望结果

暗黑主题也正常显示背景

### 实际结果

暗黑主题未正常显示背景

**Comment by timi137137** [comment]
新版本已修复
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/45f5c456-ee7d-45ba-a97b-c5a924abf539)
