### ISSUE TITLE
[setting组件] 优化项   watchEffect监听中，是否考虑去掉无意义的if条件。

### ISSUE THREAD

**Issue by quanKris** [Tencent/tdesign-vue-next-starter#603]
### tdesign-vue-next-starter 版本

1.4.1

### 重现步骤

watchEffect(() => {
  if (formData.value.brandTheme) settingStore.updateConfig(formData.value);
});
此处if判断是否存冗余?   监听变化项 一直都是 formData.value

### 期望结果

 if (formData.value.brandTheme)  可删除？会不会影响其他结果？brandTheme有默认值。

### 框架版本

Vue3

### 系统版本

win10

### Node版本

16.14

**Comment by timi137137** [comment]
这个代码没有错哦，在这个环境下如果设置有变动的时候，这行代码会将全局设置进行同步更新。如果移除可能会导致切换异常，当然这仅限于调试用w
