### ISSUE TITLE
每次切换页面路由都会调用一次登录接口？

### ISSUE THREAD

**Issue by dufu1991** [Tencent/tdesign-vue-next-starter#617]
看这句代码的意思是每次切换页面都会调用登录接口？我实际项目开发中也确实是个逻辑，但是感觉不合理。还是我使用的方式不对？
https://github.com/Tencent/tdesign-vue-next-starter/blob/cc84c85013f51887202701e12c2b7709b947018f/src/permission.ts#L27

**Comment by timi137137** [comment]
这个是合理的，在实际开发中，登录态是会随时变化的。一但后端登录态出现变化前端没有变动则会出现错误访问之类的问题，每个项目的开发方式开发方法都不一样。因此这一点按自己所需修改便是

**Comment by dufu1991** [comment]
是的，这个还是要看实际场景，我们的系统要求是登录状态放在每个接口控制，所以切换页面的时候是不需要判断的。明白了，我单独处理一下吧。感谢您的解答。
