### ISSUE TITLE
引入vuedraggable@next 滚动组件报错

### ISSUE THREAD

**Issue by Miss-huanlove** [Tencent/tdesign-vue-next-starter#618]
### tdesign-vue-next-starter 版本

^1.4.1

### 重现步骤

npm i vuedraggable@4.1.0 --save
在页面中引入import Draggable from 'vuedraggable';
项目报错
Uncaught TypeError: isFunction is not a function
    at defineComponent (runtime-core.esm-bundler.js:2252:10)
    at activity.tsx:12:16

### 期望结果

能够引入滚动组件并成功启动项目

**Comment by timi137137** [comment]
这个并非是模板问题，请给vuedraggable官方发issue

**Comment by Miss-huanlove** [comment]
引入之后并非vuedraggable报错，而是TDesign 里面的引入 import isFunction from 'lodash/isFunction';
isFunction is not a function
Uncaught TypeError: isFunction is not a function
at defineComponent (runtime-core.esm-bundler.js:2252:10)
at activity.tsx:12:16

**Comment by Miss-huanlove** [comment]
> 这个并非是模板问题，请给vuedraggable官方发issue

引入之后并非vuedraggable报错，而是TDesign 里面的引入 import isFunction from 'lodash/isFunction';
isFunction is not a function
Uncaught TypeError: isFunction is not a function
at defineComponent (runtime-core.esm-bundler.js:2252:10)
at activity.tsx:12:16

**Comment by liweijie0812** [comment]
> > 这个并非是模板问题，请给vuedraggable官方发issue
> 
> 引入后并非vuedraggable报错，而是TDesign 里面的引入 import isFunction from 'lodash/isFunction';isFunction不是一个函数未捕获类型错误：isFunction不是函数在定义组件（runtime-core.esm-bundler.js:2252:10）在活动.tsx：12:16

https://github.com/SortableJS/vue.draggable.next/issues/128 vuedraggable的问题
