### ISSUE TITLE
[td-starter init] 创建项目报错

### ISSUE THREAD

**Issue by riluocanyang** [Tencent/tdesign-vue-next-starter#619]
### tdesign-vue-next-starter 版本

0.4.1

### 重现步骤

平台：
MAC M2 芯片，Node  版本：v16.20.1

1、首先安装脚手架：
<img width="647" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/22518145/cd1e2e34-99c7-4f06-984a-d26fb7934730">

2、td-starter -v报错
<img width="649" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/22518145/e0a439af-82f5-4f51-ba7e-93316d77bf2d">

重新执行 npm i，依旧报错。

### 期望结果

可以正常初始化项目

### Node版本

16.20.1

**Comment by anhao** [comment]
同样遇到

**Comment by uyarn** [comment]
和全局的vue版本冲突 目前先解决了 升级0.4.2可以使用
