### ISSUE TITLE
mock环境地址不匹配

### ISSUE THREAD

**Issue by loganylwu** [Tencent/tdesign-vue-next-starter#629]
看起来为了支持i18n，做了API接口的路径变更。
https://github.com/Tencent/tdesign-vue-next-starter/blame/03e959696ecf412e3c062cda1e16f068be9f162a/src/api/permission.ts#L5

然而mock文件夹并未修改
https://github.com/Tencent/tdesign-vue-next-starter/blob/03e959696ecf412e3c062cda1e16f068be9f162a/mock/index.ts#L148C22-L148C22

**Comment by uyarn** [comment]
emmm 改漏了
