### ISSUE TITLE
左侧菜单优化建议

### ISSUE THREAD

**Issue by 23022340** [Tencent/tdesign-vue-next-starter#63]
当左侧菜单路由的children.length 为1的时候，目前是显示为二级菜单，只显示一级是否会更好一点。

**Comment by lovae** [comment]
> 当左侧菜单路由的children.length 为1的时候，目前是显示为二级菜单，只显示一级是否会更好一点。

全局搜一下useRenderNav这个方法，改一下生成逻辑就行了

**Comment by lovae** [comment]
> 当左侧菜单路由的children.length 为1的时候，目前是显示为二级菜单，只显示一级是否会更好一点。

全局搜一下useRenderNav方法，你会发现，在路由meta中配置 single为true就可以了

**Comment by pengYYYYY** [comment]
这边处理逻辑后续会优化一下

**Comment by qiyue2015** [comment]
> > 当左侧菜单路由的children.length 为1的时候，目前是显示为二级菜单，只显示一级是否会更好一点。
> 
> 全局搜一下useRenderNav方法，你会发现，在路由meta中配置 single为true就可以了

设置 single 为 true 后，children.length  > 1 时，也只会显示 1级。
