### ISSUE TITLE
[失败页] 失败页有个按钮缺少i18n的配置

### ISSUE THREAD

**Issue by Wyatex** [Tencent/tdesign-vue-next-starter#631]
### tdesign-vue-next-starter 版本

0.9.0

### 重现步骤

打开：[https://tdesign.tencent.com/starter/vue-next/result/fail](https://tdesign.tencent.com/starter/vue-next/result/fail)

有个按钮因为没对应的i18n配置，显示：pages.result.fail.modify

**Comment by timi137137** [comment]
closed #632
