### ISSUE TITLE
已打开tab页切换时，会闪烁整体页面下沉到底部后恢复正常

### ISSUE THREAD

**Issue by liufengvling** [Tencent/tdesign-vue-next-starter#642]
### tdesign-vue-next-starter 版本

0.9.0

### 重现步骤

来回切换上下闪烁

**Comment by timi137137** [comment]
该问题重复，模板不会解决此问题，此问题属于VueJS官方的 动画标签问题。如果不需要动画可以直接将`src/layouts/components/Content.vue`中的 
```ts
<transition name="fade">
```
标签删除即可
