### ISSUE TITLE
Eslint 规范更换为 eslint-config-alloy

### ISSUE THREAD

**Issue by Leslie-Luo** [Tencent/tdesign-vue-next-starter#643]
### 这个功能解决了什么问题

请问后续有计划将 Eslint 的规则更换为 https://github.com/AlloyTeam/eslint-config-alloy 吗？

### 你建议的方案是什么

eslint-config-alloy 拥有官方维护的 vue、typescript、react+typescript 规则，相比之下 airbnb 的 vue 和 typescript 都是第三方维护的

**Comment by timi137137** [comment]
该规则组对比现在有什么优点吗，没太看出来
