### ISSUE TITLE
main分支-0.9.0，打包报错

### ISSUE THREAD

**Issue by xiatiandegaga** [Tencent/tdesign-vue-next-starter#649]
### tdesign-vue-next-starter 版本

0.9.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/47713355/c4c3c88a-70f7-4386-b170-943baf354b46)

### 期望结果

正常打包

### 实际结果

Type 'Ref<any> | ShallowRef<any>' is not assignable to type 'string'.
  Type 'Ref<any>' is not assignable to type 'string'.

54     if (item.meta.icon) item.meta.icon = await getMenuIcon(item.meta.icon);
                           ~~~~~~~~~~~~~~

### 框架版本

0.9.0

### 浏览器版本

无

### 系统版本

window10

### Node版本

16.0.0

### 补充说明

无

**Comment by timi137137** [comment]
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/1341ab18-4294-449f-965c-3b568c4323ad)
请检查你的本地代码是否有什么diff
如果没有，那就是包管理器安装了过高版本的包导致错误
