### ISSUE TITLE
Node 版本问题

### ISSUE THREAD

**Issue by dianjie** [Tencent/tdesign-vue-next-starter#655]
### 这个功能解决了什么问题

项目指定Node版本为：
https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/package.json#L93

```
"engines": {
  "node": ">=16.0.0"
}
```
  
开发分支的这些依赖
```
"@commitlint/cli": "^18.4.1",
"@commitlint/config-conventional": "^18.4.0",
"lint-staged": "^15.1.0",
```
不支持Node.js 16。
```
"@commitlint/cli": "^17.8.1",
"@commitlint/config-conventional": "^17.8.1",
"lint-staged": "^14.0.1",
```
这些版本才支持。

### 你建议的方案是什么

依赖降级？还是修改指定的Node版本

**Comment by timi137137** [comment]
其实本身就不应该使用nodejs18以下，这一点在内部也经过了一段时间的讨论，目前我能给到的建议是使用nodejs18

**Comment by dianjie** [comment]
> 其实本身就不应该使用nodejs18以下，这一点在内部也经过了一段时间的讨论，目前我能给到的建议是使用nodejs18

那这样的话，应该把`engines`改一下吧
 ```
"engines": {
  "node": ">=18.0"
},
```
