### ISSUE TITLE
getActive函数里面的useRoute()返回的结果会出现undefined，导致点击菜单无法响应，控制台报错

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue-next-starter#659]
### tdesign-vue-next-starter 版本

0.9.0

### 重现步骤

1、下载https://github.com/Tencent/tdesign-vue-next-starter/archive/refs/tags/0.9.0.zip
2、找一台linux机器
3、npm install
4、npm run dev:linux
5、访问页面，点击菜单页面无法跳转
<img width="1113" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/15682051/e45c5605-707e-4e94-9c59-4eac262d018e">
<img width="937" alt="image" src="https://github.com/Tencent/tdesign-vue-next-starter/assets/15682051/c3e8b63c-48c0-4fad-bc8a-e618fa605f53">

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-next-starter/pull/660/files 先固定到3.3.x的vue 系28号发布的vue 3.4改动带来的问题 后面再跟进下
