### ISSUE TITLE
菜单混合模式顶部的一级菜单没用被点亮

### ISSUE THREAD

**Issue by JokerLoLgrey** [Tencent/tdesign-vue-next-starter#66]
菜单混合模式顶部的一级菜单没用被点亮
![image](https://user-images.githubusercontent.com/33446705/154318460-7bb7f193-b7cf-4700-9f18-2637a48b14ee.png)

**Comment by pengYYYYY** [comment]
收到

**Comment by JokerLoLgrey** [comment]
我看一下还是有这个问题，已经排期了吗 @pengYYYYY
