### ISSUE TITLE
Radio 单选框 用鼠标点击后再按回车键，控制台会

### ISSUE THREAD

**Issue by MrHangZai** [Tencent/tdesign-vue-next-starter#669]
### tdesign-vue-next-starter 版本

"tdesign-vue-next": "^1.6.8"

### 重现步骤

Radio 单选框 用鼠标点击后再按回车键，控制台会报错误

**Comment by maomaojiujiu** [comment]
![e2fda4ee6903df8393f5953bcf8ba03f](https://github.com/Tencent/tdesign-vue-next-starter/assets/109469652/9c2f4d1f-f13e-4d89-a157-3b9d51464634)

**Comment by liweijie0812** [comment]
修复 https://github.com/Tencent/tdesign-vue-next/pull/3896

**Comment by liweijie0812** [comment]
升级1.8.1
