### ISSUE TITLE
[path] 点击菜单无法跳转

### ISSUE THREAD

**Issue by caoqianming** [Tencent/tdesign-vue-next-starter#670]
### tdesign-vue-next-starter 版本

0.6.1

### 补充说明

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/21101210/999d1cf8-73f8-4500-9773-8ca3fcaf5d3f)

**Comment by timi137137** [comment]
请检查你实际安装的依赖版本是否与package.json中规定的版本有差异，本地未发现这种情况

**Comment by caoqianming** [comment]
这是所有的安装版本，我对了一下没什么问题。我是按照文档td-starter init 一步步来的
├── @commitlint/cli@17.8.1
├── @commitlint/config-conventional@17.8.1
├── @types/echarts@4.9.22
├── @types/lodash@4.14.202
├── @types/qs@6.9.11
├── @types/ws@8.5.10
├── @typescript-eslint/eslint-plugin@4.33.0
├── @typescript-eslint/parser@4.33.0
├── @vitejs/plugin-vue-jsx@1.3.10
├── @vitejs/plugin-vue@2.3.4
├── @vue/compiler-sfc@3.4.15
├── @vue/eslint-config-typescript@11.0.3
├── axios@1.6.7
├── commitizen@4.3.0
├── cz-conventional-changelog@3.3.0
├── dayjs@1.11.10
├── echarts@5.1.2
├── eslint-config-airbnb-base@15.0.0
├── eslint-config-prettier@8.10.0
├── eslint-plugin-import@2.29.1
├── eslint-plugin-prettier@4.2.1
├── eslint-plugin-vue-scoped-css@2.7.2
├── eslint-plugin-vue@9.20.1
├── eslint@7.32.0
├── husky@7.0.4
├── less@4.2.0
├── lint-staged@12.5.0
├── lodash@4.17.21
├── mockjs@1.1.0
├── nprogress@0.2.0
├── pinia-plugin-persistedstate@3.2.1
├── pinia@2.1.7
├── prettier@2.8.8
├── qrcode.vue@3.4.1
├── qs@6.11.2
├── stylelint-config-prettier@9.0.5
├── stylelint-less@1.0.1
├── stylelint-order@4.1.0
├── stylelint@13.13.1
├── tdesign-icons-vue-next@0.1.12
├── tdesign-vue-next@0.26.2
├── tvision-color@1.6.0
├── typescript@4.8.4
├── vite-plugin-mock@2.9.8
├── vite-svg-loader@3.6.0
├── vite@2.9.17
├── vue-clipboard3@2.0.0
├── vue-router@4.1.6
├── vue-tsc@1.8.27
└── vue@3.4.15

**Comment by caoqianming** [comment]
升级到0.9就可以了。官网默认的是0.6
