### ISSUE TITLE
[Vue 3.4] 关于 Vue3.4版本的注意事项

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next-starter#679]
由于Vue Core发布的Vue3.4新版本导致出现一系列问题，包括但不限于：

```[tasklist]
### 待解决的Issue
- [ ] #678
- [ ] #671 
- [ ] #662
- [ ] https://github.com/Tencent/tdesign-vue-next-starter/issues/698
```

目前由于Vue官方正在逐步更新修复bug，因此本模板在其稳定前

**不推荐升级至Vue3.4, 其出现导致的问题短时间内无法修复！**
**不推荐升级至Vue3.4, 其出现导致的问题短时间内无法修复！**
**不推荐升级至Vue3.4, 其出现导致的问题短时间内无法修复！**

请知悉

**Comment by billy7x17** [comment]
建议将package.json中的版本限制一下，等vue3.4bug修复后再放开
近期的新用户体验较差

**Comment by timi137137** [comment]
> 建议将package.json中的版本限制一下，等vue3.4bug修复后再放开 近期的新用户体验较差

已经限制了
