### ISSUE TITLE
官网文档能把电脑卡死

### ISSUE THREAD

**Issue by wcldyx** [Tencent/tdesign-vue-next-starter#683]
### tdesign-vue-next-starter 版本

1.8.1

### 补充说明

[文档地址](https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E5%8F%AF%E5%88%86%E9%A1%B5%E7%9A%84%E8%A1%A8%E6%A0%BC)

**Comment by timi137137** [comment]
不稳定复现，初步认为是堆大小突发过大导致

**Comment by wcldyx** [comment]
> 不稳定复现，初步认为是堆大小突发过大导致

会不会是你电脑太好了，我这边公司的i5 11 就卡死10秒，我的笔记本能直接卡死。地址是：https://tdesign.tencent.com/vue-next/components/table，你可以用笔记本试试

**Comment by wcldyx** [comment]
> > > 不稳定复现，初步认为是堆大小突发过大导致
> > 
> > 
> > 会不会是你电脑太好了，我这边公司的i5 11 就卡死10秒，我的笔记本能直接卡死。地址是：[https://tdesign.tencent.com/vue-next/components/table，你可以用笔记本试试](https://tdesign.tencent.com/vue-next/components/table%EF%BC%8C%E4%BD%A0%E5%8F%AF%E4%BB%A5%E7%94%A8%E7%AC%94%E8%AE%B0%E6%9C%AC%E8%AF%95%E8%AF%95)
> 
> 我就是笔记本，然后这个无法复现不只是我，是整个TD团队都无法稳定复现

![1709105980724](https://github.com/Tencent/tdesign-vue-next-starter/assets/26700595/6311633a-4cfc-4153-a216-2a5a612f3c40)

是表格组件，这个地址"https://tdesign.tencent.com/vue-next/components/table"卡，你可以打开这个地址页面后尝试滚动页面看看卡不卡。

**Comment by wcldyx** [comment]
> https://tdesign.tencent.com/vue-next/components/table

好吧，我同事电脑还真没卡，就我的卡
