### ISSUE TITLE
登录后提示错误：“Can't build routes”

### ISSUE THREAD

**Issue by McPorkChop** [Tencent/tdesign-vue-next-starter#696]
### tdesign-vue-next-starter 版本

latest

### 重现链接

https://tdesign.tencent.com/starter/vue-next/login?redirect=%252Fdashboard%252Fbase

### 重现步骤

官方演示网站点击登录后显示 Can't build routes
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/10668305/e0726ed7-777f-4be8-8dec-2b471593481b)

### 期望结果

正常访问

**Comment by timi137137** [comment]
请检查你的网络状态，如果确认没有问题请按F12,点击网络，然后刷新页面按登录后进行截图
