### ISSUE TITLE
左侧菜单Bug

### ISSUE THREAD

**Issue by yzkno1** [Tencent/tdesign-vue-next-starter#72]
### 重现链接
https://tdesign.tencent.com/starter/vue-next/#/list/base

### 重现步骤
预览官方案例时，发现的问题
1.将左侧菜单收起
2.打开基础列表页
![55866ad4e57a4ded8048716e8beff2f](https://user-images.githubusercontent.com/42439916/155271504-cfb3b3e5-86bd-4b6b-8108-68f4d8c1d92a.png)

### 期望结果
左侧菜单的下拉菜单不被右边表格遮盖住

### 实际结果
左侧菜单的下拉菜单会被右边表格遮盖住

| Environment | Info |
|---|---|
| 相关版本 | - |
| 框架版本 / 基础库版本 | Vue |
| 系统、浏览器 | Chrome |
| Node版本 |  |

**Comment by uyarn** [comment]
fixed https://github.com/Tencent/tdesign-vue-next-starter/pull/71
