### ISSUE TITLE
下载的模板无法引用 jsonwebtoken

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next-starter#727]
### tdesign-vue-next-starter 版本

1.9.6

### 重现步骤

下载的模板无法引用 jsonwebtoken

`
import jsonwebtoken from 'jsonwebtoken';
console.log("jsonwebtoken=>", jsonwebtoken) `

![5065977cd0edb804e705158d2bbba91](https://github.com/Tencent/tdesign-vue-next-starter/assets/78259973/7454c4e8-d793-482b-a091-728ba966a787)

### 期望结果

正常引用
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/78259973/c42d7a4d-b502-4dd4-8f0f-a2f73c791a11)

**Comment by timi137137** [comment]
这个并不是我们模板的问题，不做处理
https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility
