### ISSUE TITLE
有计划添加按钮权限控制吗？类似v-action

### ISSUE THREAD

**Issue by xiatiandegaga** [Tencent/tdesign-vue-next-starter#733]
### 这个功能解决了什么问题

解决了通用b端场景，配置按钮权限的问题

### 你建议的方案是什么

类似v-action，自动过滤按钮

**Comment by timi137137** [comment]
如果是按照按钮为颗粒度做权限控制的话有一点太细了。目前我们不考虑新增这个功能，为了开箱即用的理念我们甚至需要移除目前过多的部分功能。如果有更好的想法欢迎随时可以来讨论
