### ISSUE TITLE
[menu] 点击tab导航栏，对应菜单层级没有自动展开

### ISSUE THREAD

**Issue by Mophar-gift** [Tencent/tdesign-vue-next-starter#734]
### tdesign-vue-next 版本

1.9.7

### 重现链接

https://tdesign.tencent.com/starter/vue-next/list/base

### 直接在官方starters示例中即可复现
![image](https://github.com/Tencent/tdesign-vue-next/assets/67857649/6fe88bd8-cb0e-42ff-8b9f-3420b665ea5d)

### 期望结果

期望左侧点击、tab点击、页面刷新等操作后都能自动定位到对应层级。
（以上操作都可以通过value属性自定定位展开，而不是通过手动绑定expanded，如果这种方式不好处理，请告知如果点击tab后使menu对应层级展开）

### 实际结果

点击tab导航栏，对应菜单层级没有自动展开

### 框架版本

Vue(3.4.31)

### 系统版本

win11

### Node版本

20.9.0

**Comment by timi137137** [comment]
收到稍后跟进

**Comment by zwtderek1986** [comment]
> > > 这不是组件问题 两个组件之间本身没有直接关系 只能通过expand去控制左侧菜单的同时展开 需要在业务项目中调整代码实现的
> > 
> > 
> > 真心希望tdesign越来越好，但是用户提出可以优化的点，组件自己也可以解决的问题，需要我们修改并调整逻辑来辅助组件完成，真是奇怪了
> 
> 这个issue的问题来自于页面模板的实现，页面模板就是业务项目的原型代码，在业务项目里调整实现，这个表述有什么问题吗请问？

大哥人家只是说模版也有这个问题，我们自行在做的过程中也遇见了，所以去你们提供的模版看看喽。。。而本身人家描述存在的问题，就是既然当前激活的路由已经设置给了组件，为什么多层的展开不能触发？这个功能不是组件的么？你回答的意思是组件没问题，让我们自己去改业务代码实现。。。。。。

**Comment by uyarn** [comment]
> > > > 这不是组件问题 两个组件之间本身没有直接关系 只能通过expand去控制左侧菜单的同时展开 需要在业务项目中调整代码实现的
> > > 
> > > 
> > > 真心希望tdesign越来越好，但是用户提出可以优化的点，组件自己也可以解决的问题，需要我们修改并调整逻辑来辅助组件完成，真是奇怪了
> > 
> > 
> > 这个issue的问题来自于页面模板的实现，页面模板就是业务项目的原型代码，在业务项目里调整实现，这个表述有什么问题吗请问？
> 
> 大哥人家只是说模版也有这个问题，我们自行在做的过程中也遇见了，所以去你们提供的模版看看喽。。。而本身人家描述存在的问题，就是既然当前激活的路由已经设置给了组件，为什么多层的展开不能触发？这个功能不是组件的么？你回答的意思是组件没问题，让我们自己去改业务代码实现。。。。。。

我的意思也很明确，麻烦你仔细看清楚，这不是组件问题，页面模板实现漏了逻辑。

**Comment by timi137137** [comment]
好了好了，这个没什么需要争吵的，uy的意识只是题主发issue的地方是在组件库，组件本身不负责这个实现。消消气我这边有空就去处理

**Comment by zwtderek1986** [comment]
> > > > > 这不是组件问题 两个组件之间本身没有直接关系 只能通过expand去控制左侧菜单的同时展开 需要在业务项目中调整代码实现的
> > > > 
> > > > 
> > > > 真心希望tdesign越来越好，但是用户提出可以优化的点，组件自己也可以解决的问题，需要我们修改并调整逻辑来辅助组件完成，真是奇怪了
> > > 
> > > 
> > > 这个issue的问题来自于页面模板的实现，页面模板就是业务项目的原型代码，在业务项目里调整实现，这个表述有什么问题吗请问？
> > 
> > 
> > 大哥人家只是说模版也有这个问题，我们自行在做的过程中也遇见了，所以去你们提供的模版看看喽。。。而本身人家描述存在的问题，就是既然当前激活的路由已经设置给了组件，为什么多层的展开不能触发？这个功能不是组件的么？你回答的意思是组件没问题，让我们自己去改业务代码实现。。。。。。
> 
> 我的意思也很明确，麻烦你仔细看清楚，这不是组件问题，页面模板实现漏了逻辑。

我们也只是提个建议，因为看完市面上ui库，发现并没有在组件使用之外去做额外的处理，只是设置一下当前激活路由，组件会自动处理！刚好看见你们提供的模版也存在这个问题，就以这个为例了！不是说你组件有问题，而是说组件可以在优化一下，这么说有问题么？

**Comment by zwtderek1986** [comment]
> 好了好了，这个没什么需要争吵的，uy的意识只是题主发issue的地方是在组件库，组件本身不负责这个实现。消消气我这边有空就去处理

我们是觉得组件可以优化掉这个问题而已，在使用组件的过程中发现没有比较好处理的方式！我也尝试了用expand这个，但是发现点就多层直接就不展开了，貌似是要我自行维护，过于麻烦

**Comment by Mophar-gift** [comment]
不好意思  我是想在组件库下提issue的，看到模板里也存在这个问题，就直接提了。大家和气讨论哈，爱之深恨之切，希望这个问题可以得到大家关注哈。

**Comment by uyarn** [comment]
> > > > > > 这不是组件问题 两个组件之间本身没有直接关系 只能通过expand去控制左侧菜单的同时展开 需要在业务项目中调整代码实现的
> > > > > 
> > > > > 
> > > > > 真心希望tdesign越来越好，但是用户提出可以优化的点，组件自己也可以解决的问题，需要我们修改并调整逻辑来辅助组件完成，真是奇怪了
> > > > 
> > > > 
> > > > 这个issue的问题来自于页面模板的实现，页面模板就是业务项目的原型代码，在业务项目里调整实现，这个表述有什么问题吗请问？
> > > 
> > > 
> > > 大哥人家只是说模版也有这个问题，我们自行在做的过程中也遇见了，所以去你们提供的模版看看喽。。。而本身人家描述存在的问题，就是既然当前激活的路由已经设置给了组件，为什么多层的展开不能触发？这个功能不是组件的么？你回答的意思是组件没问题，让我们自己去改业务代码实现。。。。。。
> > 
> > 
> > 我的意思也很明确，麻烦你仔细看清楚，这不是组件问题，页面模板实现漏了逻辑。
> 
> 我们也只是提个建议，因为看完市面上ui库，发现并没有在组件使用之外去做额外的处理，只是设置一下当前激活路由，组件会自动处理！刚好看见你们提供的模版也存在这个问题，就以这个为例了！不是说你组件有问题，而是说组件可以在优化一下，这么说有问题么？

每个组件库都有自己的实现思路，我们觉得组件本身不应该过多实现路由相关的耦合逻辑，对组件本身的维护来说是个负担，仅此而已。只是我不理解我的回复有什么让你“真是奇怪了”的点，上面的回答我以为已经很清楚了。当然我没有想争吵什么的意思，可能我的反问语气让你误会了。

**Comment by zwtderek1986** [comment]
> > > > > > > 这不是组件问题 两个组件之间本身没有直接关系 只能通过expand去控制左侧菜单的同时展开 需要在业务项目中调整代码实现的
> > > > > > 
> > > > > > 
> > > > > > 真心希望tdesign越来越好，但是用户提出可以优化的点，组件自己也可以解决的问题，需要我们修改并调整逻辑来辅助组件完成，真是奇怪了
> > > > > 
> > > > > 
> > > > > 这个issue的问题来自于页面模板的实现，页面模板就是业务项目的原型代码，在业务项目里调整实现，这个表述有什么问题吗请问？
> > > > 
> > > > 
> > > > 大哥人家只是说模版也有这个问题，我们自行在做的过程中也遇见了，所以去你们提供的模版看看喽。。。而本身人家描述存在的问题，就是既然当前激活的路由已经设置给了组件，为什么多层的展开不能触发？这个功能不是组件的么？你回答的意思是组件没问题，让我们自己去改业务代码实现。。。。。。
> > > 
> > > 
> > > 我的意思也很明确，麻烦你仔细看清楚，这不是组件问题，页面模板实现漏了逻辑。
> > 
> > 
> > 我们也只是提个建议，因为看完市面上ui库，发现并没有在组件使用之外去做额外的处理，只是设置一下当前激活路由，组件会自动处理！刚好看见你们提供的模版也存在这个问题，就以这个为例了！不是说你组件有问题，而是说组件可以在优化一下，这么说有问题么？
> 
> 每个组件库都有自己的实现思路，我们觉得组件本身不应该过多实现路由相关的耦合逻辑，对组件本身的维护来说是个负担，仅此而已。只是我不理解我的回复有什么让你“真是奇怪了”的点，上面的回答我以为已经很清楚了。当然我没有想争吵什么的意思，可能我的反问语气让你误会了。

有自己的实现思路，这个我理解，也表示赞同！但是站在使用者的角度出发，也不希望把个很简单的功能搞的很复杂，而组件的开发初衷我想还是方便开发者使用吧，市面上其它大大小小的组件库也都处理了这个问题了呀！我们只是提交建议，帮助你们把产品做的完善和更好，也希望你们更好而已！

**Comment by zwtderek1986** [comment]
@uyarn 也麻烦你们看看吧，楼主提出的问题，如何解决！刷新吧，需要自行处理defaultExpanded来解决展开激活项，但是没法解决tab的切换自动展开！使用expanded，就会出现过度层的点击需要自行监听的问题，否则点击无效
