### ISSUE TITLE
请求代理 rewrite 重写地址不生效

### ISSUE THREAD

**Issue by liangxp** [Tencent/tdesign-vue-next-starter#754]
### tdesign-vue-next-starter 版本

0.10.0

### 重现步骤

vite.config.ts配置代理如下：
```
server: {
      port: 3002,
      host: '0.0.0.0',
      proxy: {
        [VITE_API_URL_PREFIX]: {
          target:VITE_API_URL,
          changeOrigin: true,
          rewrite: (path) => path.replace(/^\/api/, ""),
        }
      },
    }
```
VITE_API_URL_PREFIX这个参数就是环境变量里面的/api,这里想代理的时候去掉/api

### 期望结果

代理的时候去掉/api

### 实际结果

请求依然保持了/api

### 框架版本

"vue": "3.3.13"

### Node版本

18

**Comment by timi137137** [comment]
请详细阅读文档 -> https://tdesign.tencent.com/starter/docs/vue-next/request-data#%E8%AF%B7%E6%B1%82%E4%BB%A3%E7%90%86

**Comment by liangxp** [comment]
VITE_IS_REQUEST_PROXY = false
