### ISSUE TITLE
[husky] install command is DEPRECATED

### ISSUE THREAD

**Issue by hmingv** [Tencent/tdesign-vue-next-starter#767]
### tdesign-vue-next-starter 版本

v0.10.0

### 重现步骤

执行 `pnpm prepare`

### 期望结果

正确执行

### 实际结果

![image](https://github.com/user-attachments/assets/e647873d-b332-4fc9-86d0-813904d6ca3c)

**Comment by timi137137** [comment]
这个问题已知并在开发分支中修复，可以直接忽略。后续1.0会修复，在此将关闭issue
已修复的[代码](https://github.com/Tencent/tdesign-vue-next-starter/blob/d5cd2f5920f8d6e7321b82c93545ae2ab0e2bda8/package.json#L18)

**Comment by hmingv** [comment]
您好，请问方便问一下，现在如果要用于开发，应该克隆哪个分支比较合适呢？

V0.10.0 已经有段时间没有更新了，如果正式版本发布不了的话，可以劳烦您发布一个新的小版本吗？

**Comment by hmingv** [comment]
请问 1.0 现在有预计的发布周期吗？
