### ISSUE TITLE
[MenuContent]打包报错

### ISSUE THREAD

**Issue by china-chaim** [Tencent/tdesign-vue-next-starter#783]
### tdesign-vue-next-starter 版本

0.10.0

### 重现步骤

通过脚手架拉取的后台代码，编译没有报错信息，也没有安装过其他包。执行npm run  build 打包报错。前端路由只保留一个登录跟仪表盘，其余都是由接口下发，idea的编辑器显示代码错误，文件：src/layouts/components/MenuContent.vue，与新的拉取代码比较没有改动
![screenshot-20241104-170437](https://github.com/user-attachments/assets/6b4e6a22-6085-4ed3-bd9a-77c78e6c387c)
![20241104-171246](https://github.com/user-attachments/assets/20119d2b-89b9-4ccc-824e-75e567856a45)

![screenshot-20241104-171449](https://github.com/user-attachments/assets/d59b4e1c-7083-4344-b05c-a217eb339246)

### 系统版本

windows11

### Node版本

20.17.0

**Comment by china-chaim** [comment]
[package.json](https://github.com/user-attachments/files/17616230/package.json)
[package-lock.json](https://github.com/user-attachments/files/17616231/package-lock.json)

**Comment by china-chaim** [comment]
把node_modules文件夹删除后重新拉去后报错信息
![1](https://github.com/user-attachments/assets/21177821-5b7b-4a17-8804-e12976b70d1b)
![2](https://github.com/user-attachments/assets/9995e698-0094-42da-97c6-f919e87910c4)

**Comment by china-chaim** [comment]
新安装后打包报错完整文件，编译没任何问题
[build-error.log](https://github.com/user-attachments/files/17626025/build-error.log)

**Comment by timi137137** [comment]
这个报错明显是 本地的tsconfig.json缺失了，他不应该出现任何有关node_modules相关（我看见你没删改了个名报错是肯定的）
![image](https://github.com/user-attachments/assets/a7bf5f2f-da2e-4240-b28e-1d67ad3e05f8)

**Comment by china-chaim** [comment]
名字是在报错信息复制下来之后再改的，本地tsconfig.json只加了"allowJs": true，以及更改noImplicitAny，其他没有更改过。找不到问题的也可以等你们新的版本脚手架拉取后可以直接打包，我再把代码转移过去
![233](https://github.com/user-attachments/assets/3fb7a46b-e167-4a5b-8832-689352d78371)
