### ISSUE TITLE
[lint] npm run lint，提示版本问题

### ISSUE THREAD

**Issue by xorsheng** [Tencent/tdesign-vue-next-starter#790]
### tdesign-vue-next-starter 版本

0.11.0

### 重现步骤

未改动源码，直接使用模板，安装后运行npm run lint 提示版本问题

### 实际结果

> @tencent/tdesign-vue-next-starter@0.11.0 lint
> eslint --ext .vue,.js,.jsx,.ts,.tsx ./ --max-warnings 0

=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=4.3.5 <5.4.0

YOUR TYPESCRIPT VERSION: 5.4.5

Please only submit bug reports when using the officially supported version.

=============

### Node版本

18

**Comment by timi137137** [comment]
该问题已知，可以忽视。后续会统一更新

**Comment by timi137137** [comment]
duplicate #768
