### ISSUE TITLE
系统设置里面切换导航布局为第二个，横板显示的时候，为什么顶部导航栏只有1级菜单，二级菜单哪去了？

### ISSUE THREAD

**Issue by whr2349** [Tencent/tdesign-vue-next-starter#96]
### tdesign-vue-starter 版本

是，最新版0.2.0 cli

另外一个问题，布局的第一个和第三个没有发现变化，侧边导航栏并没有变色

**Comment by whr2349** [comment]
@uyarn 好的，👌

**Comment by uyarn** [comment]
@whr2349 布局一
菜单是可伸缩的 
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/26377630/159437027-3d7dbbc8-093d-46a4-972b-e3cd323c15ba.png">
布局三 头部为整体 菜单不可伸缩
<img width="1495" alt="image" src="https://user-images.githubusercontent.com/26377630/159437252-60ad19be-adf1-4c88-b948-be6bfb243e9f.png">

另外提到的侧边栏不变色能不能贴个图 不知道具体说的是哪里

**Comment by wanganlin** [comment]
> @whr2349 布局一 菜单是可伸缩的 <img alt="image" width="1501" src="https://user-images.githubusercontent.com/26377630/159437027-3d7dbbc8-093d-46a4-972b-e3cd323c15ba.png"> 布局三 头部为整体 菜单不可伸缩 <img alt="image" width="1495" src="https://user-images.githubusercontent.com/26377630/159437252-60ad19be-adf1-4c88-b948-be6bfb243e9f.png">
> 
> 另外提到的侧边栏不变色能不能贴个图 不知道具体说的是哪里

布局一左侧菜单的背景颜色，默认能否是深颜色？
![image](https://user-images.githubusercontent.com/1684390/159603683-3328e85d-494e-413e-a64a-105680f153ea.png)

**Comment by uyarn** [comment]
@wanganlin 有需要可以自己改一下layouts/components/Sidenav里面 t-menu的theme 我们初始化的暂时不会改

**Comment by wanganlin** [comment]
@[uyarn](https://github.com/uyarn) 收到，谢谢。
