### ISSUE TITLE
自定义主题色中，无法保存并使用通过色板调色选取的主题色

### ISSUE THREAD

**Issue by candy-Tong** [Tencent/tdesign-vue-next-starter#99]
### tdesign-vue-next-starter 版本

latest

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/list/base

### 重现步骤

1. 通过色板选择一个颜色
![image](https://user-images.githubusercontent.com/20377280/159866011-582c0d97-43cd-4094-9144-012aeeff98a9.png)
2. 点击复制配置项
```json
{
    "showFooter": true,
    "isSidebarCompact": false,
    "showBreadcrumb": false,
    "mode": "light",
    "layout": "side",
    "splitMenu": false,
    "isFooterAside": false,
    "isSidebarFixed": true,
    "isHeaderFixed": true,
    "showHeader": true,
    "backgroundTheme": "blueGrey",
    "brandTheme": "dynamic"
}
```
这份配置没有关于色板颜色的配置，复制到项目中是没有办法知道刚刚选择的颜色是什么的

### 期望结果

支持色板自定义主题色

### 实际结果

色板的自定义主题色无法保存

**Comment by uyarn** [comment]
这个问题需要依赖组件的能力来修复 目前暂时记录一下 接下来会处理的。
